momocus/sakazuki

.github/workflows/ruby.yml, .rubocop.yml, Gemfile, Gemfile.lock, Rakefile, app/controllers/sakes_controller.rb, app/jobs/application_job.rb, app/models/sake.rb, app/views/sakes/_sake.json.jbuilder, config/application.rb, config/environments/development.rb, config/environments/production.rb, config/environments/test.rb, config/initializers/backtrace_silencers.rb, config/initializers/content_security_policy.rb, config/initializers/wrap_parameters.rb, config/puma.rb, test/channels/application_cable/connection_test.rb, test/controllers/sakes_controller_test.rb, test/test_helper.rb
LintとCIを回して、開発を楽にしてこ。
- Rubocopを導入した
- いい感じの設定.rubocop.ymlを追加した
- GithubActionsを追加した
=> Rubocop & GithubActionsを追加した

.rubocop.yml, config/spring.rb
=> Fix: rubocopのカンマについて設定忘れの項目を追加した

.rubocop.yml, db/seeds.rb
- 日本語を許可
- db以下のファイルを一部対象にした
- その他リファクタリング
=> Rubocopの設定を変更した

.rubocop.yml, app/mailers/application_mailer.rb, config.ru, config/boot.rb, config/environment.rb, config/initializers/assets.rb, test/models/sake_test.rb
=> Rubocopの設定ミスで文字列クオート判定がオフになっていたのをオンにした

.github/workflows/ruby.yml, scripts/check_endoffile_with_newline.sh
反省して。
対象はトップディレクトリの全ファイルを拡張子で指定している。
一部、node_moduleなどのディレクトリを対象外に設定した。
=> ファイル末尾に改行があるかチェックするスクリプトをGithub Actionsに入れた

app/views/sakes/_form.html.erb, app/views/sakes/edit.html.erb, app/views/sakes/index.html.erb, app/views/sakes/new.html.erb, app/views/sakes/show.html.erb, config/locales/models/ja.yml
- bootstrapを適用した
- 順番を、表示義務あり、表示義務なし、家で開けてから、の順にした
- 一部入力方法をスライダやファイルうpにした
- 一部、デフォルト値をいれた
=> 酒詳細のデザインを更新した

.eslintignore, .eslintrc.js, .github/workflows/js-ts.yml, .prettierrc.js, app/javascript/packs/application.js, app/javascript/packs/clickable_sakeindex.ts, app/javascript/packs/hello_typescript.ts, app/views/sakes/index.html.erb, config/webpack/environment.js, config/webpack/loaders/typescript.js, config/webpacker.yml, package.json, scripts/check_endoffile_with_newline.sh, tsconfig.json, yarn.lock
生のJavaScriptはやはり人の書くものではない。
今後、味グラフをつくるにあたってTypeScriptを導入しました。
- ブラウザでJSが警告を出していたので修正
- TypeScriptを導入
- JS/TS用のlinterであるeslintの導入
- eslintを行うGithubActionsを作成
- すでにあるindexにおけるテーブルクリックするJSを、TSで置き換えた
=> TypeScriptを導入した

.eslintrc.js, .github/workflows/js-ts.yml, .github/workflows/ruby.yml, package.json, yarn.lock
- ESLint無駄な設定を削除
- 実行方法を`yarn eslint`を`yarn lint`に変更
追加
- GithubActionsが無駄にまわるのを修正
- 2つしかテストがないのに、PRだと4つ回っていた
- PRを対象外にして、pushで回すようにした
=> ESLintをリファクタした

Gemfile, Gemfile.lock, config/database.yml, db/migrate/20200510073627_create_sakes.rb, db/migrate/20200710091954_change_columns_to_sakes.rb, db/migrate/20200712013358_rename_state_columns_to_sakes.rb, db/migrate/20200712015709_change_warimizu_to_sakes.rb, db/schema.rb, package.json
- HerokuがPostgreSQLを使うので、PostgreSQLを使うための設定をした。
- dev環境でもSQLiteではなくPostgreSQLを使うようにした。
- PostgreSQLを何らかの方法でインストールする
- PostgreSQLのインストール方法が下記にそれぞれちょっとずつ違う方法が載っていて、どれが一番いいのかわからない。（私は真ん中のやつを使った）
- https://www.postgresql.org/download/linux/ubuntu/
- https://wiki.postgresql.org/wiki/Apt
- https://docs.microsoft.com/ja-jp/windows/wsl/tutorials/wsl-database#install-postgresql
- ~~sudo passwd postgres して、PostgreSQLをインストールしたときにデータベースの管理ユーザーとして作られた"postgres"に対してパスワードを設定する~~
- ターミナルを再起動する
- sudo service postgresql start してPostgreSQL サーバーを起動
- sudo -u postgres psql を実行して、ユーザー名・パスワードを設定する
```
$ sudo -u postgres psql
postgres=# create role <username> with createdb login password '<password>';
postgres=# \q
```
- config/database.ymlのdevelopment以下に、↑で設定したのと同じusername, passwordを書く
```yml
development:
<<: …
```
=> Heroku上で動くようにした

app/javascript/src/stylesheet/application.scss, app/views/devise/passwords/edit.html.erb, app/views/devise/passwords/new.html.erb, app/views/devise/registrations/edit.html.erb, app/views/devise/sessions/new.html.erb, app/views/devise/unlocks/new.html.erb, app/views/layouts/_header.html.erb, app/views/layouts/application.html.erb, app/views/sakes/_form.html.erb, app/views/sakes/show.html.erb
close #103 
- 画面サイズの大きなスマホでもスマホレイアウトになるようにした
- スマホ時に全体の左右のスペースをなくした
- スマホ時に文字サイズを1.2倍にした
=> スマホ時に文字を大きくした

app/controllers/sakes_controller.rb, app/views/sakes/_form.html.erb, app/views/sakes/show.html.erb
PR #118 の後にマージすること
Fix #116 
- BYにnilを入力できるようにした
- 古酒や通年酒など、BYはわからないこともある
- new/editで入る数値のデフォルト値の設定をviewからcontrollerに移した
- Fix #116 と同様の修正方法で、よりよい実装方法を見つけた
=> 酒newでBYのデフォルト表記を現在日時のBYにした

README.md, cli-scripts/run-all-checks.sh
close #123
とりあえず最小限の記述。
- READMEに貢献方法を追記した
- CONTRIBUTIONファイルに書く方法もあるけど、まだそこまで大げさにしなくていいと思う
- 全チェックを走らせるスクリプトを追加した
=> Contributionを追加した

app/controllers/sakes_controller.rb, app/javascript/src/stylesheet/application.scss, app/views/sakes/index.html.erb
- 検索したあと、検索を維持したままソートできる
- 既存のソート機能を削除した。
- 既存のRansackによる検索と共存しつつ、Ransackで新たなソート機能を実現した。
=> ソート機能をRansackで実現した

.dockerignore, Dockerfile, README.md, config/database.yml, docker-compose.yml, entrypoint.sh
Replace #85
- いてづきさんのPRのコミットをスカッシュした
- ももかすさんのコミットを取り込んだ
- 一部READMEを修正した
- 間違いを修正
- Lintをかけた
- 言い回しを一部修正
=> Add docker by iteduki

spec/helpers/sakes_helper_spec.rb
=> SakesHelperのRSpecを追加した

README.md
=> mvだと差分に出てくるのでcpにしたい

app/views/sakes/_form.html.erb
#163 のあとに見てね
とりあえず_form.html.erbだけ修正しました。
他のファイルも元気があるときにちまちま修正していこうと思います。
=> _form.html.erbで括弧が省略されていた箇所を修正

app/javascript/src/stylesheet/application.scss, app/views/sakes/_sake-buttons.html.erb
=> 新規作成ボタンが上に乗ってページ送りボタンが押せない不具合の修正

.gitignore, .rubocop.yml
#188 の仕切り直し。
styleguide を inherit しても現状、特に差分ありません
=> cookpad/styleguide を inherit する

spec/support/sign_in_module.rb, spec/system/signin_redirect_integrating_drinkbutton_spec.rb
close #204
- raiseにメッセージを書いた
- 書け、無名メッセージ絶対許さない
=> サインインリダイレクトとdrink buttonの結合テストを追加

Gemfile, Gemfile.lock, app/assets/config/manifest.js, app/javascript/packs/application.js, app/views/sakes/_drink-button.html.erb, app/views/sakes/_float-button.html.erb
- gem bootstrap-iconsの削除
- node packageのbootstrap-iconsとそのiconフォントを使うことにした
- application.jsの整理
- Rails6の書き方にした
=> Before Bootstrap5

spec/spec_helper.rb, spec/support/capybara.rb, spec/system/drink_buttons_spec.rb, spec/system/sign_in_redirect_spec.rb, spec/system/signin_redirect_integrating_drinkbutton_spec.rb
Close #209
- js: trueでドライバを切り替えられるようにした
- Capybaraの設定が複数のファイルに分かれて書いてあったので、Capybara.rbに集約した
- systemテストでドライバ設定していた箇所を修正
=> CapybaraとRspecの設定見直し

spec/system/drink_buttons_spec.rb
merge after #214 
同じことの繰り返しがあったので、書き直し
=> drink buttonテストをスッキリさせた

app/javascript/packs/sakes_show.js, app/javascript/src/stylesheet/application.scss, app/javascript/src/stylesheet/sakes_show.scss, app/javascript/src/typescript/lightbox.ts, app/views/sakes/show.html.erb
=> Fix simplelightbox

.erb-lint.yml, app/views/devise/confirmations/new.html.erb, app/views/devise/mailer/reset_password_instructions.html.erb, app/views/devise/mailer/unlock_instructions.html.erb, app/views/devise/passwords/edit.html.erb, app/views/devise/passwords/new.html.erb, app/views/devise/registrations/edit.html.erb, app/views/devise/sessions/new.html.erb, app/views/devise/shared/_links.html.erb, app/views/devise/unlocks/new.html.erb, app/views/layouts/_header.html.erb, app/views/layouts/application.html.erb, app/views/sakes/_form.html.erb, app/views/sakes/edit.html.erb, app/views/sakes/index.html.erb, app/views/sakes/new.html.erb, app/views/sakes/show.html.erb, app/views/sakes/show_photo.html.erb
Close #198
*.erbのみ、マクロ化されたメソッド（link_to、render等）呼び出し時のカッコ省略を禁止した。
=> *.erbのみマクロ化されたメソッド呼び出し時のカッコ省略を禁止する

.github/workflows/test.yml, app/models/concerns/searchable.rb, app/views/elasticsearch/index.html.erb, config/initializers/elasticsearch.rb, docker-compose.yml, dotenv.example
=> Elasticsearch導入その3

app/helpers/sakes_helper.rb, app/views/sakes/_form.html.erb, config/locales/models/ja.yml
=> BYに不明を選べるようにした

app/controllers/application_controller.rb, app/controllers/sakes_controller.rb, app/controllers/users/registrations_controller.rb, config/locales/controllers/application.ja.yml
#232 の後にPRにする
close #203 
- 日本語化されていなかった、updateメッセージをi18n化
- 日本語化されていなかった、一部deviseメッセージをi18n化
- controllerのi18nは`config/locales/controllers/application.ja.yml`にまとめていこうと思うけど、どうかな
=> 一部日本語化されていないフラッシュメッセージをi18nで日本語化した

app/packs/src/stylesheet/common.scss, app/views/layouts/_footer.html.erb, app/views/layouts/application.html.erb, config/locales/controllers/application.ja.yml
close #239
close #245
- 酒の感想ライセンス、CC BY 4.0でいいよね
- 改変や商用利用を許可していいと思う
=> Add: footerにOSSリンクと酒感想のライセンスを明記した

config/initializers/ransack.rb
=> RansackのソートアイコンをBootstrap Iconsにした

app/views/layouts/_header.html.erb, config/locales/views/layout.ja.yml
=> Update: ヘッダーのハンバーガーメニューの日本語化(#268)

app/views/sakes/_drink-button.html.erb
=> Refactor: 酒の開封状態によらず、未評価ならば評価するボタンを表示する

app/views/sakes/_form.html.erb, app/views/sakes/index.html.erb
- グラフのラベルを上と右にもつけたら、スマホでグラフが小さい！！
- グラフがいるセルの余白を小さくしてグラフを大きくした
- 酒indexは画像セルを小さくしてグラフを大きくした
=> グラフサイズを大きくした

README.md, docker-compose.yml
=> Fix: rakeタスクの実行に必要なファイルをbindの対象にした(#301)

.github/workflows/check.yml, .github/workflows/test.yml
もう我々のキャッシュ方法は古かった
- GitHub Actionsのcacheを最新のものに更新した
- ちょっとしたリファクタを入れた
あらかんたん！
- https://github.com/actions/cache/blob/main/examples.md
=> GitHub Actionsのキャッシュ方法を最新のものにした

app/packs/src/javascript/bootstrap_plugins.js, app/views/layouts/_flashes.html.erb
「邪魔なら私を好きに消していいのよ」
- flashメッセージに閉じるボタン「✕」をつけた
- これをそのまま適用しただけ
- <https://getbootstrap.jp/docs/5.0/components/alerts/#dismissing>
=> Add: flashメッセージにcloseボタンをつけた

app/controllers/elasticsearch_controller.rb
Close #312
note: 
ローカル環境でElasticsearchのデータを全件削除したいときは、下記コマンドを実行する
```shell
curl -XDELETE 'http://localhost:9200/*'
```
=> Fix: 酒が一件も登録されていないときのエラー修正(#312)

config/locales/models/sake.ja.yml
=> Update: bottle_stateの日本語を開封状態に変更

app/views/sakes/_float-button.html.erb, app/views/sakes/_form.html.erb, app/views/sakes/index.html.erb, app/views/sakes/show.html.erb
スラッシュが入っているとRubocopが反応しない。
設定値はStyle/WordArrayのWordRegexで変えられる。
設定値を変えるほどではない？
- <https://docs.rubocop.org/rubocop/cops_style.html#stylewordarray>
=> Refactor: Word Arrayを%w記法で書き直した

README.md, app/helpers/application_helper.rb, app/views/layouts/application.html.erb, dotenv.example
close #352
お酒を管理するとお酒を買うお金が湧く、かもしれない
- AdSenseを書き出す関数を書いた
- production環境でAdSenseが設定されるようにした
- dotenvか引数でクライアントIDを指定する必要がある
- READMEに追記した
- Herokuにて`GOOGLE_ADSENSE_CLIENT`の設定をする
- とりあえず自動の広告を入れるが、うざったくないか？
- うざったかったら、自分で指定の広告を入れる？
=> Google AdSenseを追加した

app/views/sakes/_form.html.erb
Fix #368
酒の名前のオートコンプリートいらなくない？
=> Update: 酒フォームで酒の名前でのオートコンプリートをしないようにした

app/packs/entrypoints/common.scss, app/views/layouts/_footer.html.erb
Fix #367
フッターの文字が色々あって揃ってなかった。
ついでにscssでの要素指定もやめた。よくない。
=> Update: フッターの文字の左右の位置を他要素と揃えた

app/controllers/sakes_controller.rb, app/views/sakes/index.html.erb
=> Update: 空ボトル込みの表示のときのみページネーションするようにした

app/controllers/sakes_controller.rb
close #374
after #373
詳細はIssue #374 参照
=> 酒indexにおけるN+1問題を修正

app/views/sakes/_sakagura-datalist.html.erb, cli-scripts/get_sakagura.rb, cli-scripts/sakagura-list.ndjson
close #377
- 酒蔵スクリプトに井村屋株式会社を追加
- スクリプトを実行し、酒蔵リストを更新
- 既存関数の名前を合わせるために修正
=> 酒蔵リストに井村屋株式会社を追加

app/models/sake.rb, app/views/sakes/_form.html.erb
close #384 
いい感じのバリデーションを追加した。
HTML上で入力中にガードするのはやってない。
=> 酒のデータのバリデーションを追加した

app/packs/entrypoints/sakes/index.scss, app/views/sakes/_drink-button.html.erb, app/views/sakes/index.html.erb
=> 酒indexにおける酒瓶状態とdrink-buttonの上下をセンター揃えにした

.github/workflows/codeql.yml, app/controllers/sakes_controller.rb
自動でコードをセキュリティスキャンしてくれるすごいやつだよ、ガシャーンガシャーン
GitHub Security Labが作ってるすごいツール。
とりあえずJS・TS・Rubyを対象で動かした。
push・PRとさらに土曜の朝にセキュリティスキャンしてくれるすごいやつだよ。
=> Add: CodeQLによる自動解析を入れた

app/helpers/sakes_helper.rb, app/packs/entrypoints/sakes/show.scss, app/views/sakes/_show_detail.html.erb, app/views/sakes/_show_review.html.erb
繰り返しを避けた。
これで酒showのmasterマージ準備が整うはず。
=> 新デザイン酒showのスタイルシートを整理した

app/views/sakes/_form.html.erb
fix #414
リセットボタンを消したときにスタイル指定が間違っていた。
=> Fix: モバイル表示でグラフが小さくなる不具合を修正

app/views/layouts/_flashes.html.erb
=> Add: flashメッセージに小さな影を追加した

app/packs/entrypoints/common.scss, app/views/layouts/application.html.erb, app/views/sakes/_show_abstract.html.erb
=> Update: フラッシュメッセージとヘッダーの間の隙間を削除

Procfile, Procfile.dev, dotenv.example
after #430
close #408
HerokuがProcfileないって怒ってる。
Rails7でProcfile.devがレポジトリに入ったし、Procfileもレポジトリに入れておこう
- HerokuデフォルトRuby動作をProcfileとして追加
- Procfile.devにDockerを使ったおすすめコマンドを、コメントにて追加
=> Procfileをレポジトリに含めた

Gemfile, Gemfile.lock, app/helpers/application_helper.rb, app/javascript/application.js, app/views/layouts/application.html.erb, config/cable.yml, package.json, yarn.lock
=> Revert: Turboの導入をリバートした

app/helpers/application_helper.rb, app/uploaders/image_uploader.rb, app/views/sakes/show.html.erb
でかい画像はバエル。
#172 に関連。
フルには解決してない。
=> Update: Twitter Cardででかい画像にした

app/javascript/autocompletion/complete_meigara.ts, spec/system/sake_form_completion_from_names_spec.rb
=> 銘柄から蔵名を補完して登録しても、蔵名と地域が保存されない不具合を修正

app/views/layouts/_header.html.erb, config/locales/views/layout.ja.yml, spec/requests/sake_request_spec.rb, spec/views/layouts/_header.html.erb_spec.rb
- ヘッダーのハンバーガーメニューにお品書きへのリンクを追加した
- sakes/menu のrequest specを追加した
=> ヘッダーのハンバーガーメニューにお品書きへのリンクを追加した

app/javascript/autocompletion/complete_meigara.ts, app/javascript/rating/rating.ts, app/javascript/simple_lightbox/simple_lightbox.ts, app/javascript/sync_dom/sync_bindume_date.ts, app/javascript/sync_dom/sync_kura_todofuken.ts, app/javascript/taste_graph/input_taste_graph.ts, app/javascript/taste_graph/show_taste_graph.ts
=> Refactor: もはや必要ないDOMContentLoadedイベントを使わなくした

app/javascript/application.js
=> ブラウザでディベロッパーツールを開いたときに出るエラー修正

config/initializers/kaminari_config.rb
Fix #483
note:
ページ下部の余白はindexだけでなくshowでも気になったので別Issueにしました #485
=> ページネーションの調整

app/assets/stylesheets/application.scss, app/views/kaminari/_paginator.html.erb, app/views/layouts/_footer.html.erb, app/views/layouts/application.html.erb
fix #485
- footerの上部にマージンをつけた
- デザイン検討の邪魔になるので、paramsのデバッグ表示をfooterの下に移動した
=> Update: footerの上部にマージンをつけた

app/controllers/sakes_controller.rb, app/views/sakes/index.html.erb, config/initializers/ransack.rb
close #482
使ってないソート機能は削除だ！
- Remove: 酒indexのソート機能を削除した
- Refactor: ソート機能の削除により、酒コントローラのindexをシンプルに書き直した
=> ソート機能を削除した

app/views/sakes/index.html.erb, spec/system/sake_index_total_spec.rb
fix #529 
- Add: 酒総量のテストを追加した
- Fix: 空き瓶込みのときの酒の総量が間違っていたのを修正
=> 空き瓶を表示したときの酒の総量が間違っているのを修正

app/views/sakes/_form_review.html.erb
close #549
総合評価である好みの星をつけるのは最後のほうでよい。
=> Update: 酒フォームのレビューのスターをレビュー下部に移した

app/uploaders/image_uploader.rb
Close #537
酒画像を.webpに変換してアップロードし、サイズが小さくなるようにした
=> 画像アップロード時に.webpに変換してサイズを小さくした

Gemfile
fix #561
なんでもかんでもdev&testグループにいれてはいけない！
=> Fix: Gemfileのgroupを正しくした

app/javascript/sakes_show.js, app/javascript/share/share.ts, app/views/sakes/_show_abstract.html.erb, app/views/sakes/_sns_share_button.html.erb, config/locales/helpers/share.ja.rb
Close #548
- twitterとFacebookのシェアボタンを消した
- [Web_Share_API](https://developer.mozilla.org/ja/docs/Web/API/Web_Share_API)を呼び出すシェアボタンを追加した
=> WebShareAPIを使ってシェア

app/controllers/application_controller.rb, app/controllers/sakes_controller.rb, app/controllers/users/invitations_controller.rb, app/controllers/users/registrations_controller.rb, app/javascript/taste_graph/input_taste_graph.ts, app/javascript/taste_graph/show_taste_graph.ts, app/javascript/taste_graph/taste_graph.ts, app/views/sakes/_sake.json.jbuilder, app/views/sakes/index.json.jbuilder, app/views/sakes/show.json.jbuilder, package.json, spec/requests/sake_request_spec.rb, yarn.lock
~~大きなPRになりそうなので、featureブランチへの小さなPR3回くらいに分けた。~~
これはマスターへマージして、次からをfeatureブランチにする。
Turbo導入するぞ！！の前準備
- 導入前準備 ←今ここ
- Turbo導入
- Stimulus導入
- Refactor: flashメッセージをredirect_toのオプション引数で呼び出すようにした
- flashはセッションの一種で、特に`flash[:key] = msg`はmsgを次の遷移後に出すの意。
- そのため、flashにいれてからredirectのほうがわかりやすいと思う
- Remove: jsonレスポンスを削除
- 使ってない、かつ、メンテされていない。そのため、新しいDBカラムの値が含まれないという問題もある。
=> Turbo導入の前準備

app/javascript/simple_lightbox/simplelightbox.d.ts
ﾁｮﾄｶﾀﾜｶﾙ
少し型わかってきた。
これで前より補完が強力になる。
=> Update: SimpleLightboxの型ファイルを最新版に追従した

.eslintrc.json, app/javascript/autocompletion/complete_detail.ts, app/javascript/taste_graph/taste_graph.ts, package.json, yarn.lock
TypeScriptにもドキュメント書き始めたし、チェックいれとこう！
https://github.com/microsoft/tsdoc
=> ESLintにTSDocのチェックを入れた

Gemfile, Gemfile.lock
commit 696404a416d902ffdfa9590329c507ad26926358 の消し忘れ
=> Remove: jsonレスポンスで使うjbuilder gemを削除

Gemfile, Gemfile.lock, spec/support/capybara.rb
今までの、「なんで動いてたんだ」を「正しく動いているね」に！
これを導入すると、Issue #202 がやりやすくなる。
- Remove: webdrivers gemを削除
- Fix: Capybaraドキュメント通りrequireを追加
- Fix: テスト時のdriverを具体的に指定した
=> Capybaraの設定の見直し

app/controllers/application_controller.rb, app/controllers/sakes_controller.rb, app/controllers/users/invitations_controller.rb, app/controllers/users/registrations_controller.rb, app/helpers/application_helper.rb, app/views/devise/registrations/edit.html.erb, app/views/layouts/_header.html.erb, app/views/layouts/application.html.erb, app/views/sakes/_drink_button.html.erb, app/views/sakes/show.html.erb, config/initializers/devise.rb, spec/requests/sake_request_spec.rb
Turboをいれたら、各種を対応だ！
まだテストは通らない。
- Turboドキュメントに従う変更
- HTTPステータスコードの変更
- pack_tagでのreload設定の追加
- patch/deleteの書き方の変更
- DeviseをTurboに対応
=> Turboのインストール後の変更

spec/factories/sakes.rb, spec/system/bottle_level_datetimes_spec.rb
=> emptied_at, opened_atまわりのテストを修正

.github/workflows/codeql.yml, .github/workflows/fly.yml
=> Fix: Actionsでブランチ名にmasterが残っていたのをmainに修正した

.github/workflows/auto-assign.yml, .github/workflows/check.yml, .github/workflows/codeql.yml, .github/workflows/esbuild-bundle-analyzer.yml, .github/workflows/fix-command.yml, .github/workflows/fly.yml, .github/workflows/slash-command-dispatch.yml, .github/workflows/test.yml
close #733
- Actionsのバージョンを現在の最新版にした
- ~~バージョン指定はメジャーバージョン一桁指定`@v3`形式で固定した~~
- バージョン指定はなるべくメジャーバージョン指定とした
- ただし、auto assignとhadolintはメジャーバージョンのみ指定ができないので例外
=> Update: 各種Actionsを現在の最新バージョンにした

app/javascript/completion/detail_dict.ts, app/models/sake.rb, config/locales/enums/sake.ja.yml, spec/system/sake_form_completion_for_detail_spec.rb
close #722
一回火入れとだけ書いてある日本酒に対応していこう
- 一回火入れを追加
- 補完とテストも追加
=> 火入れの選択肢に一回火入れを追加

app/views/sakes/_form_abstract.html.erb
close #724
- 酒formで画像をトップに持って行った
- 酒viewの画像の位置は変えてない
- スクショ
- #724
=> 酒編集の画像を一番上にした

.github/workflows/check.yml, cli-scripts/run-all-checks.sh, fly.Dockerfile
Dockerにも公式でcheckツールが入っていた！
- Docker Build Checksを追加
- run-all-check.sh
- GitHub ActionsのCheck
- docker build checksに従い修正
- Docker Build Checksの紹介ブログ
- https://www.docker.com/blog/introducing-docker-build-checks/
- Docker Build Checksのドキュメント
- https://docs.docker.com/build/checks/
- 名前はなんなんだ、Docker Build Checksでいいのか？
- docker buildコマンドのサブコマンドとして存在する現状
- Docker Checkではない
=> Docker Build Checksを導入した

docker-compose.yml
=> docker-compose.ymlのバージョンを削除

.erb-lint.yml, app/views/devise/confirmations/new.html.erb, app/views/devise/invitations/edit.html.erb, app/views/devise/invitations/new.html.erb, app/views/devise/mailer/invitation_instructions.html.erb, app/views/devise/mailer/invitation_instructions.text.erb, app/views/devise/passwords/edit.html.erb, app/views/devise/passwords/new.html.erb, app/views/devise/registrations/edit.html.erb, app/views/devise/sessions/new.html.erb, app/views/devise/shared/_links.html.erb, app/views/devise/unlocks/new.html.erb, app/views/kaminari/_next_page.html.erb, app/views/kaminari/_page.html.erb, app/views/kaminari/_prev_page.html.erb, app/views/layouts/_footer.html.erb, app/views/layouts/_header.html.erb, app/views/layouts/application.html.erb, app/views/sakes/_drink_button.html.erb, app/views/sakes/_float_button.html.erb, app/views/sakes/_form_abstract.html.erb, app/views/sakes/_form_detail.html.erb, app/views/sakes/_form_review.html.erb, app/views/sakes/_sake.html.erb, app/views/sakes/_show_abstract.html.erb, app/views/sakes/index.html.erb, app/views/sakes/show.html.erb, app/views/shared/_error_messages.html.erb, config/locales/views/devise.ja.yml
**featureブランチへのマージ**
- Rubocop設定の変更に伴い、ERBLintの設定を変更
- ERBLintでオートコレクト・手動修正した
これでERBLintも落ちない！
=> 新たなRubocopの設定にERBLintの設定を追従・修正した

.erb-lint.yml, .github/workflows/check.yml, .rubocop-erb.yml, .rubocop.yml, Gemfile, Gemfile.lock, app/views/sakes/_form_review.html.erb, app/views/sakes/_rating.html.erb, app/views/sakes/_show_abstract.html.erb, cli-scripts/run-all-checks.sh
**featureブランチへのマージ**
- rubocop-erbを導入
- rubocop-erbによる指摘をオートコレクト・手動修正
- rubocop-erbとerblintで設定を共有
=> Rubocop ERBを導入した

.erb-lint.yml, .github/workflows/check.yml, .rubocop-erb.yml, .rubocop.yml, Gemfile, Gemfile.lock, app/views/sakes/_form_review.html.erb, app/views/sakes/_rating.html.erb, app/views/sakes/_show_abstract.html.erb, cli-scripts/run-all-checks.sh
after #826 
**featureブランチへのマージ**
Rails7.2から入ったbrakemanを導入した。
SQLインジェクションとかセキュリティチェックをしてくれるすごいやつだよ。
- brakemanの導入
=> Brakemanを導入した

CONTRIBUTING.md, README.md
close #567
- CONTRIBUTING.mdを作成した
- ついでにREADME.mdの内容をメンテした
=> CONTRIBUTING.mdを作成

app/views/layouts/_header.html.erb, package.json, yarn.lock
close PR #800
DependabotによるアップデートでCIが解決できないので手動PR
- markuplintを4.11.4にアップデート
- ハンバーガーメニュー内の仕切りバーをやめた
=> Markuplintを4.11.4にアップデートした

app/controllers/sakes_controller.rb
fix #969
いままでなぜ動いてたかはわからん！
- `photos: []`をpermiteに追加
=> 酒画像をアップロードするとログが流れるのを修正

app/controllers/concerns/sakes_photos.rb, app/controllers/sakes_controller.rb
after #986 #978
- 酒の画像に関する機能をconcerns化
=> 酒コントローラーの画像に関する機能を分割

app/controllers/concerns/sakes_photos.rb, app/controllers/concerns/sakes_search.rb, app/controllers/sakes_controller.rb, app/models/concerns/bottle_state_timestampable.rb, app/models/sake.rb, spec/system/bottle_state_timestamps_spec.rb
fix #613 
どんどんやっていこうね
- #986
- #1011 
- #1012
=> Feature/concerns/base Fat酒コントローラーのリファクタ

fly.toml
fix #1026
- Issue #1026 の方針に従い、
- 環境変数をfly.tomlに追加
- Fly.ioのSECRETから変数を削除（実施済み）
=> Add: prod環境用の環境変数をfly.tomlに追加

app/helpers/application_helper.rb
=> Update: Google AdSenseが設定されていないときはタグを出さないようにした

.github/workflows/check.yml, .github/workflows/test.yml, CONTRIBUTING.md
close #1095 
- check.yml 内の Check Actions でまわす Linter の並列化
- node/ruby などは同じ環境を使いまわすままにした
- test.yml の Test Actions の発火条件を、テスト関係ファイルの変更のみにした
良い感じ
=> Actionsの高速化
