app/assets/stylesheets/sakes.scss, app/views/sakes/index.html.erb, app/views/sakes/show.html.erb
Fix #37 
- テーブルの行全体をクリックして詳細が見れるようにした
- jQueryとcssで実現した
- 参考：https://qiita.com/Kohei_Kishimoto0214/items/2e56985552926d025c35
- 各酒の削除・編集は詳細ページに異動した
=> 酒一覧を少しかっこよくした

.github/workflows/ruby.yml
aptはCLIでの使用を非推奨のため、GithubActionsに警告ログが出る。
そのため、apt-getを使うように変更した。
ついでにオプションを追加し、推奨依存関係をインストールしないようにした
=> GithubActionsでaptをやめてapt-getを使うようにした

app/javascript/packs/application.js, app/javascript/packs/taste_graph.ts, app/views/sakes/_form.html.erb, package.json, yarn.lock
登録と編集で味・香りをグラフで入力できるようにするぞ
一部は別PRにする
- chart.jsとchart.js用のTypeScript型を導入した
- 味香りグラフでの入力を実装した
- chart.jsを使いTypeScriptで実装した
- 味・香りは0~6の7段階で、3を中央値としている
- 画像表示はまだ
#　試し方
- TypeScriptが含まれるため、`bundle exec rails server`の前に1度`./bin/webpack`でコンパイルをすること
=> 味・香りグラフを追加した

.erb-lint.yml, .github/workflows/ruby.yml, Gemfile, Gemfile.lock, app/views/devise/mailer/reset_password_instructions.html.erb, app/views/devise/mailer/unlock_instructions.html.erb, app/views/devise/passwords/edit.html.erb, app/views/devise/passwords/new.html.erb, app/views/devise/registrations/edit.html.erb, app/views/devise/sessions/new.html.erb, app/views/devise/shared/_error_messages.html.erb, app/views/devise/shared/_links.html.erb, app/views/devise/unlocks/new.html.erb, app/views/layouts/_footer.html.erb, app/views/layouts/application.html.erb, app/views/layouts/mailer.html.erb, app/views/sakes/_form.html.erb, app/views/sakes/edit.html.erb, app/views/sakes/index.html.erb, app/views/sakes/new.html.erb, app/views/sakes/show.html.erb
- https://github.com/Shopify/erb-lint
- ERB Lint
- 古いオリジナルがあるが更新されていない
- これはShopifyがforkしたプロジェクトで、Shopifyでも使われなくなってきているらしい
- ときどき更新遅れで、Rubocopのアップデートで動かなくなる
- とりあえず最新のRubocopで動くので、動く間はLintすることにする
- 動かなくなったら、取り除くことも考える
- ERB Lintを追加
- 設定は全Linterをオンにしている
- erb自体のチェックと、erbに埋め込まれたRubyコードをチェックする
- 一部、埋め込みRubyと相性が悪いRubocopルールがあり、それをオフにしている
- 横幅は120文字とした
- ERB LintのGitHub Actionsを追加
- ERB Lintに従い既存のerbファイルを修正した
- 120文字で頑張る、できれば80文字が好き
- 各種Rubyのいい感じ書き方にした
- ダブルクオート！
- `map { |k| ... }`は駄目で、`map do |k| ... end`がいいらしい
- `<br />`のような`/>`閉じはXHTMLの作法で、HTML5では使わない
=> ERB Lintを追加した

app/models/search/base.rb
- PostgreSQL移行後、検索ができなくなった問題を修正した
- 原因
- PostgreSQLでは"WHERE LIKE"をtext型のデータ検索にしか使えないため(SQLiteでは、"WHERE LIKE"でtext型もinteger型も検索できる)
- 現在検索対象のカラムのうち、integer型であるbottle_levelとtokutei_meishoがエラーとなる
- 対策
- 検索するときにカラムのデータをtext型にキャストする
- 備考
- text型にキャストすることで検索速度の低下のおそれがある。
- 将来的に全文検索に対応する。そのときに検索機能は一新する予定なので、現時点では検索速度を考慮しない。
=> PostgreSQL移行による検索機能のバグ修正

app/assets/stylesheets/sakes.scss, app/assets/stylesheets/sakes_index.scss, app/javascript/packs/form_graph.ts, app/javascript/packs/index_graph.ts, app/javascript/packs/taste_graph.ts, app/models/sake.rb, app/views/sakes/_form.html.erb, app/views/sakes/index.html.erb, config/locales/models/ja.yml
Fix #2
- なんと酒一覧がよりかっこよくなったよ！
- あとは酒の画像だけ
- 酒一覧にグラフ表示した
- あんま重たくないのでグラフは当初の予定と違って画像化してない
- 酒一覧のデザインを2段組にしたよ、今後タグとかより情報を足していきたいね
- 酒の新規・編集で味・香りを入力なしにできるようにした
- リセットボタンが追加された
- 味香りの値がない酒は空グラフが表示される
=> 味・香りグラフを酒一覧に追加した

Gemfile, Gemfile.lock
ソース： https://github.com/rroblak/seed_dump
本番環境でも開発環境でもデータをダンプしたくなるかもしれないので、どちらの環境で使えるようにしておいた
使用例: dbから酒のデータをダンプしてseed.rbに追記するコマンド
```
bundle exec rails db:seed:dump MODELS=Sake APPEND=true
```
=> Add: dbからseed.rbにデータをダンプするgemを追加

app/helpers/tweet_helper.rb, app/views/sakes/show.html.erb, config/locales/models/ja.yml
close #34
- 酒のshowにTweetボタンを追加した
- Tweetボタンを押すツイッターの投稿画面に飛ぶ
- Tweet内容には酒の名前、蔵の名前、色、香り、味が入る。
- 末尾の「。」のありなしでいい感じに「。」を入れたり入れなかったりする。
- Tweet内容には`#Sakazuki`のハッシュタグが入る
- Twitterの仕様から、末尾にいらない#が入る
- gemのtweet-buttonは使わなかった
- tweet-buttonはLink Shareのみ対応しており、ハッシュタグShareに対応していない
- tweet-buttonは使うと巨大な<html>を生成するため、かなり巨大なタグが生成される
- ja.ymlを使って記述しているが、日本語のみに対応している。
- "萩野酒造さんの萩の鶴"と"Haginotsuru of Hagino Shuzo"のように、英語だと文章の順番が変わるため面倒。
=> Tweetボタンを追加した

app/controllers/sakes_controller.rb, app/helpers/sakes_helper.rb, app/models/search/base.rb, app/models/search/sake.rb, app/views/devise/passwords/edit.html.erb, app/views/devise/passwords/new.html.erb, app/views/devise/registrations/edit.html.erb, app/views/devise/sessions/new.html.erb, app/views/devise/unlocks/new.html.erb, app/views/sakes/_form.html.erb, app/views/sakes/index.html.erb, app/views/sakes/show.html.erb, app/views/sakes/show_photo.html.erb, config/locales/models/ja.yml
Fix #80
- 空き瓶をデフォルトでは非表示にした
- 古い機能の在庫表示は削除した
- 酒のデフォルト表示を新しい順にした
- idによる降順でソートされる
- 酒のソート機能を追加した
- 特定名称、都道府県、開封状態の昇順でソートできる
- テーブルヘッダーで昇順降順の変更
- 現状の酒一覧のテーブルがレスポンシブデザインかつ構造が複雑なテーブルになっている
- そのためうまくテーブルにヘッダーがつけられない
- モデルへのインデックスの付加
- 昇順降順を頻繁かつ大量のモデルに使うなら、モデルへインデックスを付加して高速化する必要がある
- https://techracho.bpsinc.jp/hachi8833/2018_01_11/50793
=> 酒一覧をより見やすくする機能強化 作り直し

app/javascript/src/stylesheet/application.scss, app/uploaders/image_uploader.rb, app/views/sakes/_form.html.erb, app/views/sakes/index.html.erb, app/views/sakes/show.html.erb
- 酒の画像サイズをいままでより大きくした
- 酒の画像を閲覧端末に応じて適切なサイズで表示できるようにした。
- IndexやShowビューに表示するサムネイル画像は縦横比1:1でトリミングして、並べた時に綺麗に整列するようにした
- 画像アップロード時のサイズ制限or圧縮
=> 酒の画像サイズを大きく＆レスポンシブにする

.github/workflows/gem.yml, .github/workflows/node.yml, .stylelintrc.json, README.md, app/javascript/src/stylesheet/application.scss, cli-scripts/run-all-checks.sh, package.json, yarn.lock
今後のPRの自動チェックのためにLintをさらに追加した。
- [markdownlint](https://github.com/igorshubovych/markdownlint-cli)の追加
- [stylelint](https://stylelint.io/)の追加
- LintをGitHub Actionsと`run-all-checks.sh`へ追加
- Lintエラーの反映
=> MarkdownとStylesheetのLintを追加した

.erb-lint.yml, app/controllers/sakes_controller.rb, app/helpers/sakes_helper.rb, app/models/sake.rb, app/views/sakes/index.html.erb, config/initializers/ransack.rb
- 空き瓶にチェックを入れる
- 検索すると、空き瓶も表示される
- 空き瓶は普段使わないので、「チェックを入れる」→「検索する」、の2段階でアクセスさせる形式にした
- その後、検索や空き瓶表示の状態を引き継いでソートもできる
- 古い空き瓶リンクを削除
- Ransackでデフォルトのidソートと空き瓶表示機能を実現
- Ransackのリファクタ
- 検索クエリにわかりやすい別名をつけた
- Ransackの検索クエリに間違いがあると実行時エラーになるようにした
- 必要なかったERBLintの設定を消した
=> Ransackを使って空き瓶表示機能を作成した

.dockerignore, Dockerfile, README.md, docker-compose.yml
- slimイメージを使い開発用Dockerイメージをコンパクトにした
- 中途半端なDockerイメージを、Macでの開発用に仕上げた
- おそらくMacでの開発に使えるはず
- https://evilmartians.com/chronicles/ruby-on-whales-docker-for-ruby-rails-development
- https://iriya-ufo.net/blog/2019/08/14/rails-dev-env-on-docker/
=> 開発用Dockerイメージをコンパクトに仕上げた

cli-scripts/run-all-checks.sh
ElasticSearch導入にあたり、Dockerfileが複数になる予定である。
現状のDockerfileのチェックは、プロジェクトのトップディレクトリにDockerfileが一つだけ存在する前提でチェックをしている。このため、Dockerfileが複数になったときにチェックを行えない。
下記のいずれの場合でも、Dockerfileをgithub actionsでチェックできるようにした
- Dockerfileが一つの場合
- Dockerfileが拡張子違い（dev.Dockerfile など）で複数存在する場合
- 異なるディレクトリにDockerfileが複数存在する場合
=> Dockerfileが複数存在するときにgithub actionsでチェックできるようにした

Gemfile, Gemfile.lock, README.md, app/controllers/sakes_controller.rb, app/models/concerns/searchable.rb, app/models/sake.rb, app/views/layouts/_header.html.erb, config/elasticsearch.yml, config/initializers/elasticsearch.rb, config/routes.rb, docker-compose.yml, dotenv.example, lib/tasks/elasticsearch.rake
- ElasticSearchでstring型とtext型のフィールドを対象に、日本語による全文検索をできるようにした
- ElasticSearch用の検索BOXはheaderに仮置き
- DockerでElasticSearchを動かせるようにした 
- enumのフィールド（特定名称や加水など）も文字列検索できるようにする
- DBの更新があったときにElasticSearchにデータを送る処理を非同期で行えるようにする
- ElasticSearchを実行し、検索結果を表示する専用のビューをつくる
- ElasticSearch用の検索BOXをどこか適切な場所に配置する（悩み中）
- 検索結果をハイライトする
- elasticsearch
- <https://www.elastic.co/jp/downloads/elasticsearch>
- 日本語解析用のプラグイン
- <https://www.elastic.co/guide/en/elasticsearch/plugins/current/analysis-kuromoji.html>
- <https://www.elastic.co/guide/en/elasticsearch/plugins/current/analysis-icu.html>
```sh
$ elasticsearch
```
```sh
$ curl http://localhost:9200/
...
```
```sh
$ bundle exec rake environment elasticsearch:import:model CLASS='Sake' FORCE=y
...
```
=> Elasticsearchその1

app/controllers/elasticsearch_controller.rb, app/controllers/sakes_controller.rb, app/models/concerns/searchable.rb, app/views/elasticsearch/index.html.erb, app/views/layouts/_header.html.erb, config/locales/views/ja.yml, config/routes.rb
#150 のつづき
- ElasticSearchを実行し、検索結果を表示する専用のページをつくった(<http://localhost:3000/elasticsearch>)
- 画面サイズやサインイン状態によらず、ヘッダーに常時ハンバーガーメニューを表示するようにした
- ElasticSearch用の検索BOXをヘッダーのハンバーガーメニューに入れた
enumのフィールド（特定名称や加水など）も文字列検索できるようにする
DBの更新があったときにElasticSearchにデータを送る処理を非同期で行えるようにする
検索結果のハイライト表示
テストの追加
=> Elasticsearch導入その2

app/views/sakes/_form.html.erb
- アップロードするファイルを選ぶとき、画像ファイル以外は選べないようにした。
画像ファイル以外が選べない様子↓
- _form.html.erbで括弧が省略されている箇所の修正
- 変更が混ざるのが嫌なのでプルリク分けます
=> アップロードするファイルを選ぶとき、画像ファイル以外は選べないようにした

yarn.lock
dependabotのセキュリティアラート(CVE-2021-28092)解消のため、
yarn upgradeした
=> Fix: CVE-2021-28092

app/javascript/src/stylesheet/application.scss, config/locales/models/ja.yml
Closes #94
こんなもんでどうでしょうか。
選択された画像は、赤いボーダーと ❌  アイコンで、削除されるっぽい見た目にしています。
チェックボックスは隠しました。
チェックボックスは、そこしかクリックできないような印象が出てしまいますが、
実際は画像全体が label で囲まれていてクリック可能領域です。
=> 酒画像削除時の選択状態をボーダー色とアイコンで強調

app/helpers/sakes_helper.rb, app/models/sake.rb, app/views/sakes/_update-sake-bottle-button.html.erb, app/views/sakes/index.html.erb, config/locales/models/ja.yml, spec/models/sake_spec.rb, spec/spec_helper.rb, spec/system/drink_buttons_spec.rb
close #185 #162
酒を開けると、評価もしないといけなかった。
酒を開けるのと評価するのを分けた。
酒indexには酒を開けるボタンと、開けて評価するボタンを追加した。
また、開けているが未評価の酒には評価するボタンが表示される。
=> Add: 酒を評価するボタンを追加した

Gemfile, Gemfile.lock, app/controllers/sakes_controller.rb, app/helpers/sakes_helper.rb, app/javascript/src/typescript/sync_bindume_date.ts, app/views/sakes/_form.html.erb, spec/helpers/sakes_helper_spec.rb
Closes #170 
* `form.date_select` では、ラベルのフォーマットをカスタマイズできるようですが、和暦を埋め込むようなことはできなさそうでした。
このため、`<select>` を組み立てるヘルパーメソッドを定義しました。
* 西暦→和暦変換には https://github.com/tomiacannondale/era_ja を使いました。
<details>
<summary>📸 スクリーンショット</summary>
修正したほうがわかりやすそう？
</details>
=> 製造年月日&BY に和暦を追加

app/controllers/application_controller.rb, app/views/layouts/_header.html.erb, app/views/sakes/_sake-buttons.html.erb, spec/rails_helper.rb, spec/support/sign_in_module.rb, spec/system/sign_in_redirect_spec.rb
fix #171
- ユーザーが酒作成ボタンからログインしたとき、酒作成ページに飛ばされるようにした。
- ユーザーが酒編集ボタンからログインしたとき、酒編集ページに飛ばされるようにした。
- ユーザーが任意のページからヘッダーのSign-inボタンを押してログインしたとき、ログインする前にいたページに戻されるようにした。
- ただしSign-inページのヘッダーからSign-inボタンを押してログインしたときは、Sign-inページではなくインデクスに飛ばされる。
やってないこと
- indexの「評価する」ボタンや「開封する」ボタンなどからログインしたときの挙動の検討
- 現状はなりゆきで以下の挙動をします
- 「評価する」ボタンクリック後にログインしたらeditページへ遷移
- 「開封する」「空にする」ボタンクリック後にログインしたらindexページへ遷移し、bottle_levelは変更されない
=> 酒作成でログインしたときインデクスに戻されないようにした

app/views/devise/sessions/new.html.erb, app/views/sakes/edit.html.erb, app/views/sakes/show.html.erb, spec/support/capybara.rb, spec/system/drink_buttons_spec.rb, spec/system/signin_redirect_integrating_drinkbutton_spec.rb
無条件にsleepしていたが、テストごとにどんどん遅くなるのでやめた。
ページタイトルに仕込んだtestidをfindで読み込むことでページ遷移を認識するようにした。
- 以下のような無意味に見えるテストが残るが、書き直しておくべきかどうか。
```ruby
wait_for_page new_user_session_path
expect(page).to have_current_path new_user_session_path
```
=> Update: RSpecテストのページ遷移待ちを高速化した

app/javascript/src/typescript/input_taste_graph.ts, app/javascript/src/typescript/show_taste_graph.ts, app/javascript/src/typescript/taste_graph.ts, app/views/sakes/index.html.erb
Issue #121 関係、場合によっては閉じる。
- 酒indexの味香りグラフ・画像をモバイル表示で2段組にした
- 味香りグラフのドットサイズを調整した
- index/showは小さく、formはそのままに
- 酒showの味香りグラフのドットを小さくしたが、大きくしたままが大変で諦めた。
=> 味香りグラフのサイズを変更した

Dockerfile, Gemfile, Gemfile.lock, app/views/elasticsearch/index.html.erb
#224 が動かなかったので修正した
e3d62a8
bootstrap5化によるviewの変更を忘れていたので対応した。
24e3117
[elasticsearch-rails](https://github.com/elastic/elasticsearch-rails)が現状ruby3対応しておらず、DBのデータをelasticsearch側にimportするときにエラーが起こる。[修正のプルリク](https://github.com/elastic/elasticsearch-rails/pull/992)は出ていたがreleaseがいつになるかは不明。https://github.com/elastic/elasticsearch-rails/issues/989#issuecomment-826519648 で、せっかちな人はこうしてねと書かれていた方法に従った。
githubのリポジトリを指定しgemをダウンロードするため、docker環境にもgitをインストールした。
=> elasticsearchを動くようにした

app/helpers/sakes_helper.rb, app/models/sake.rb, app/views/sakes/index.html.erb, spec/helpers/sakes_helper_spec.rb, spec/models/sake_spec.rb
- 日本酒の量を尺貫法で酒indexに表示した
- これで在庫が一瞬で丸わかり
- 買いすぎも飲みすぎも防げるね
- 開封済みの酒瓶は半量を計算することにし、ざっくり計算にした。
- ここに表記でいいのか？
=> 日本酒の在庫量を表示するようにした

app/views/elasticsearch/index.html.erb, app/views/sakes/index.html.erb
近接デザイン、関係あるものは近くに。
- 検索フォームをinput-group化
- ついでに空き瓶スイッチを即時反映化した
- スイッチはステータスが即時反映されるべき、そう人間は思っている
=> 検索文字列と検索ボタンをinput-group化してまとめた

app/controllers/application_controller.rb, app/controllers/sakes_controller.rb, app/views/layouts/_flashes.html.erb, app/views/sakes/_form.html.erb, app/views/sakes/show.html.erb, config/locales/controllers/application.ja.yml, spec/support/capybara.rb, spec/system/drink_buttons_spec.rb, spec/system/sake_create_spec.rb, spec/system/sake_update_spec.rb
Close #197
- Indexで開封する・空にするボタンを押したあとIndexにリダイレクトするようにした。
- ユーザーが誤って開封する・空にするボタンを押してしまったときには修正できるように、酒編集後に表示するflashメッセージに酒詳細ページへのリンクを入れた。
- おまけに、酒作成や削除時のFlashメッセージに酒の名前を表示するようにした。
=> Indexで開封する・空にするボタンを押したあとIndexにリダイレクトするようにした

app/views/sakes/index.html.erb, config/locales/views/sake.ja.yml, spec/system/edit_in_index_page_spec.rb
毎回showを開いてeditボタンを押して、こんな煩雑な苦悩からついに開放だ！
- 酒indexの各酒に編集リンクを追加した
- 編集リンクがあって動作する！というめちゃ簡単なテストをTDDで追加した
- `ja.yml`を #251 と共有化できるかも
=> 酒indexの各酒に編集ボタンを追加した

app/helpers/devise_helper.rb, app/helpers/sakes_helper.rb, app/helpers/tweet_helper.rb, app/models/sake.rb, config/locales/helpers/tweet.ja.rb, spec/support/capybara.rb, spec/support/sign_in.rb
Close #237
note: 正規表現でマッチした箇所を後方参照して置換した
検索文字列: `@param\s(\[.+\])\s([a-zA-Z0-9_]+)`
置換文字列: `@param $2 $1`
=> Fix: yardoc 引数の書き方を修正する #237

Gemfile, Gemfile.lock, app/views/sakes/_float-button.html.erb, app/views/sakes/_form.html.erb, app/views/sakes/index.html.erb, app/views/sakes/show.html.erb, config/locales/views/sake.ja.yml
close #186
- 酒フォームのアコーディオン化
- アコーディオンで意味をつけたので、表示義務のバッジを削除
- 酒フォームの登録・更新ボタンのfloat-button化
- 薄い色のボタンにボーダーを追加
- turbolinksがgemとnpmで重複してたので使っていないgem側を削除
- turbolinksの動作で不具合を踏んだので修正
- 新規登録、drink-buttonによるアコーディオンの動作の検討
- 評価するとかだと味わいアコーディオンを開きたい
- 味わいにフォーカス？URLフラグメントを使う？BAD UIにならないか？
- 評価ボタンで酒瓶状態のスタイル強調？
=> 酒フォームのアコーディオン化

app/packs/src/stylesheet/common.scss, app/views/layouts/_footer.html.erb, app/views/sakes/_float-button.html.erb
fix #258
- 画面サイズが小さいときはfooterの下方向の余白を増やした。
- 画面サイズが小さいときはfloat-buttonの下方向の余白を小さくした。
=> float-buttonがfooterに被らないようにした

app/packs/src/stylesheet/bootstrap_custom.scss, app/packs/src/stylesheet/common.scss, app/views/devise/confirmations/new.html.erb, app/views/devise/passwords/edit.html.erb, app/views/devise/passwords/new.html.erb, app/views/devise/registrations/edit.html.erb, app/views/devise/sessions/new.html.erb, app/views/devise/unlocks/new.html.erb, app/views/elasticsearch/index.html.erb, app/views/sakes/_drink-button.html.erb, app/views/sakes/_form.html.erb, app/views/sakes/edit.html.erb, app/views/sakes/index.html.erb, app/views/sakes/new.html.erb, app/views/sakes/show.html.erb
close #261.
- 今までは見出しがh2から始まっていた
- 理由はh1タグでのBootstrapデフォルト文字サイズが大きすぎて見栄えが悪いから
- 見出しh1はブラウザや検索クローラから特殊扱いされることがあり、1ページに1つが推奨されている
- 見出しタグをh1から始めた
- 合わせてh3以降の見出しも順番通り使うように変更した
- Bootstrapをカスタマイズしてh1文字サイズを調整した
- 内容は[Wiki](https://github.com/momocus/sakazuki/wiki/Design)に書いておいた
- 見出しh1部がヘッダーと近すぎたため、微調整した
=> ページ見出しをh1から始めるようにした

app/views/sakes/_drink-button.html.erb, app/views/sakes/_form.html.erb
float-buttonにつけたボーダーをdrink-buttonのバッジにもつけた。
見やすいでしょ？
- drink-buttonバッジにボーダーを追加した
- drink-buttonの評価するボタンを共通化リファクタリングした
- 香味グラフのリセットボタンの見た目を、他の押せるボタンと共通化した
=> drink-buttonバッジの薄い色にボーダーを追加した

app/packs/src/typescript/show_taste_graph.ts
close #259
1行で治ったわ
- TS/JSの発火イベントをDOMContentLoadedからturbolinks:loadに変更した
- turbolinksされないTS/JSの発火イベントはDOMContentLoadedのまま。
- 問題が起こるページ遷移は酒indexにしかなさそうなので、問題が起きたら考えるlazy。
=> turbolinksによってグラフが消える不具合を修正

Gemfile, Gemfile.lock, app/controllers/users/InvitationsController.rb, app/models/user.rb, app/views/devise/invitations/edit.html.erb, app/views/devise/invitations/new.html.erb, app/views/devise/mailer/invitation_instructions.html.erb, app/views/devise/mailer/invitation_instructions.text.erb, app/views/devise/shared/_links.html.erb, app/views/kaminari/_paginator.html.erb, app/views/layouts/_header.html.erb, config/initializers/devise.rb, config/routes.rb, db/migrate/20210829172516_add_devise_invitable_to_users.rb, db/schema.rb, spec/system/user_invitation_spec.rb
#67
Adminユーザーから招待メールを送ってユーザー追加できるようにした。
使ったgemはこちら-> https://github.com/scambra/devise_invitable
招待するリンクはとりあえずヘッダーに配置した。（※リンクは移設予定なので翻訳していない。）
招待された側にはメールが届く。
---
やっていないこと: 
ユーザー管理画面はまだない。たとえばこんなの↓
https://railstutorial.jp/chapters/updating_and_deleting_users?version=4.2#sec-showing_all_users
ユーザー管理画面をつくったら、現在ヘッダーに置いているInvitationボタンを移設する。
また、ユーザー管理画面から、Adminがほかのユーザーを削除したり、Admin権限を持つユーザーを増やせるようにしよっかな～って考えてる。
=> ユーザー招待制にした

config/initializers/cloudinary.rb
fix #275
今までは特に設定をしていなかった。
そのため古いSDKではHTTPのURLが生成される可能性があった。
そこでCloudinaryの設定を変更し、常にHTTPSを強制するようにした。
参考：
https://cloudinary.com/documentation/cloudinary_sdks#configuration_parameters
=> CloudinaryのURLにhttpsを強制するようにした

app/views/sakes/index.html.erb, config/initializers/ransack.rb
close #279
Issue #126 に関連
味・香りのソート欲しくなったの。
- 味・香りソートを追加
- ソート項目が横長になったので早めに折り返されるようデザインを調整
- 味・香りソートで未評価（NULL）を最小値と扱うようにした
- Ransackがアップデートされたら:nulls_always_lastを使ってどんなソートでもNULLは最後にしたい
- 現状、5月に実装済みだが、リリースバージョンに乗っていない
=> 味・香りでのソートを追加した

app/views/kaminari/_gap.html.erb, app/views/kaminari/_next_page.html.erb, app/views/kaminari/_page.html.erb, app/views/kaminari/_paginator.html.erb, app/views/kaminari/_prev_page.html.erb
ページネーションの細かな改善。
スマホでも結構入りきる。
- 小さな画面サイズでもページネーション番号を隠さず表示するようにした
- ページネーションの「前」「次」ボタンを、Bootstrap Iconsの「＜」「＞」にした
- ページネーションの「＜」「＞」ボタンを常に表示するように統一した
=> 小さい画面でページネーションを隠さないようにした

app/views/sakes/show.html.erb, spec/system/sake_create_spec.rb
Close #269
酒Showページのh1見出しを酒の名前にした。
visibility:hiddenのdivタグ作ってwait_for_page用のdata-tesidをつけたけど、これでいいかな？
=> 酒Showページのh1見出しを酒の名前にした 

app/views/elasticsearch/index.html.erb, config/locales/views/elasticsearch.ja.yml
Close #286 
翻訳に失敗してElasticsearchページの見出しが「Title」になっていたのを直した
=> Elasticsearchページのh1見出しを修正

app/packs/src/typescript/taste_graph.ts
fix #125
close #270
- グラフの4象限に色付けした
- グラフの左右上下に濃淡についてラベル文字列を追加した
- グラフの点の色を茜色にした
- グラフの色の濃さはどの程度がいいのか
- グラフの味と香りの色合いを変えるべきか
- アクセントカラーは本当に茜色でいいか
- グラフの色を象限分けじゃなくグラデーション化
- 香りが高い、の文字の回転。chart.jsにはないのでプラグインで内部文字列オブジェクトを書き換える？
- https://github.com/chartjs/Chart.js/issues/3535
=> 味香りグラフの濃淡をわかりやすくした

app/controllers/sakes_controller.rb, app/helpers/application_helper.rb, app/views/devise/confirmations/new.html.erb, app/views/devise/invitations/edit.html.erb, app/views/devise/invitations/new.html.erb, app/views/devise/passwords/edit.html.erb, app/views/devise/passwords/new.html.erb, app/views/devise/registrations/edit.html.erb, app/views/devise/sessions/new.html.erb, app/views/devise/unlocks/new.html.erb, app/views/elasticsearch/index.html.erb, app/views/layouts/application.html.erb, app/views/sakes/edit.html.erb, app/views/sakes/index.html.erb, app/views/sakes/new.html.erb, app/views/sakes/show.html.erb
Close #288
各ページのタイトル（ブラウザのタブに表示されるテキスト）を、"h1見出し - SAKAZUKI"となるようにした。
=> ページのタイトルを個別に変えた

Gemfile, Gemfile.lock, package.json, yarn.lock
Bundlerによって入るRailsはすでに6.1.4になっていた。
しかしRails向けのnodeパッケージが6.1.1のままだった。
そのため、こちらも6.1.4に揃えた。
=> Update: Rails用のnodeパッケージを6.1.1から6.1.4にアップデートした

spec/helpers/sakes_helper_spec.rb, spec/models/photo_spec.rb, spec/models/sake_spec.rb, spec/requests/sake_request_spec.rb, spec/system/drink_buttons_spec.rb, spec/system/edit_sake_spec.rb, spec/system/new_sake_spec.rb, spec/system/sign_in_redirect_by_drinkbutton_spec.rb, spec/system/sign_in_redirect_spec.rb, spec/system/user_invitation_spec.rb, spec/views/sakes/index.html.erb_spec.rb
RSpec書こうとしたら気になる点が多かったので先に整理
- RSpecのファイル名と配置を見直した　
- 上記をすることで、必要なくなったRSpecのtype指定を削除した
- 一部viewテストでcapybaraを使うためにtype: systemを指定した
=> RSpecのファイル名とtype指定のリファクタ

package.json, yarn.lock
Fix #334
Bootstrapのバグだったようだ。
5.1.1で再現。
5.1.3で修正されている。
=> 酒indexのソートボタンのデザインが崩れるのを修正

public/robots.txt
Fix #292
- `noindex`や`nofollow`をしておくと、クローラからのアクセス不可を減らせるぞ！
- robots.txtを編集して、ユーザ関係とエラサー関係をクローラ対象外にした
- meta-tagsジェムを使っての`noindex/nofollow`の指定
- 新しいページやリンクごとに指定を考えるのが手間
- 設定値が各viewに散らばり、一元管理できない
=> Update: robots.txtでクローラの除外設定をした

app/controllers/sakes_controller.rb, app/models/sake.rb, db/migrate/20211004074321_add_open_and_empty_days_to_sakes.rb, db/schema.rb, spec/factories/sakes.rb, spec/models/sake_spec.rb
これでバリバリ酒モデルを安全に作れる！
- 酒モデルのopened_at/emptied_atカラムにnot nullバリデーションを追加
- not nullバリデーションのspecを追加
- 酒DBカラムのデフォルトを変更
- 前は`now()`クエリだったが、これだと`Sake.new`したときにはまだデフォルト値が入らない
- 固定値`2021-01-01 00:00:00`に変更した
- DBに送るクエリ回数を減らした
- `update` x2よりも`assign_attributes` x2のち`save`が優秀:+1:
=> 酒モデルのopened_at/emptied_atにバリデーションを追加した

Gemfile, Gemfile.lock, package.json, yarn.lock
fix #307
Bootstrapの依存先のバグも修正されたし、ついに上げてYarn v3を使う準備をするぞ！
- Webpackerを5.4.3に上げた
=> Update: Webpackerを5.4.3にあげた

.eslintrc.js, .github/workflows/check.yml, app/packs/channels/consumer.js, app/packs/channels/index.js, app/packs/entrypoints/common.js, cli-scripts/run-all-checks.sh, package.json
プロジェクト内に設定ファイルとしてのjsファイルが結構ある。
ESLintかけたりPrettierかけたりしていきたい。
- `.js`ファイルにもTypeScript設定のESLintをかけていた
- `eslint-disable`マジックコメントを適宜つけていた
- JavaScriptとTypeScriptで設定の違うESLintが走る！
- JSとTSでESLintの設定が変わるようにした
- JSをベースにして、TSの設定をoverridesで実現した
- JSのESLintはインデント、改行、ダブルクオート、セミコロンなしの基本セットを追加した
- 必要なくなったeslint-disableを削除
- @typescript-eslint/no-unused-vars-experimentalの使用をやめた
- typescript-eslintのv5.0.0で削除予定
- そもそも@typescript-eslint/no-unused-varsのオプション設定で同じことを実現できた
- 実体に従い、Yarnのscript名を変更した
- `yarn lint-ts`を`yarn run lint:eslint`のように変更
=> ESLintがJavaScriptでもTypeScriptでも正しく動くようにした

.eslintrc.js, package.json
after #348
`yarn run lint:eslint:XXX`を整理した
- `yarn run lint:eslint`の対象をPrettierと同じくした
- 対象が増えたのでESLintで「ダブルクオートを含む文字列をシングルクオートとするのを許可」ルールを追加
- Prettierに揃えて`yarn run lint:eslint:fix`コマンドを追加した
=> ESLintコマンドをPrettierのコマンドと揃える設定にした

.github/workflows/fix-command.yml, .github/workflows/slash-command-dispatch.yml
close #349
after #353
手動でESLintしてPrettierしてRubocopして…、つまらないことは自動化した！
- 開発者「頑張ってPR出したぞ！」
- GitHub Actions「だめでーーーすwww」
- オーナー「直して（コマンドで自動で直す方法あるから簡単だよ）」
- 開発者「直さないと。でもどうやって。コマンドもわからん。PRやめよ」
[こんな感じになる](https://github.com/momocus/sakazuki/pull/355)
- 開発者「頑張ってPR出したぞ！」
- GitHub Actions「だめでーーーすwww」
- オーナー「自動で直すわ"""/fix"""」
- オーナー「自動で直ったからおk or 自動で直らないところあるから直して」
- 開発者「やるぞー！」
1. Public Repositoryに許可権限を持つPersonal Access Tokenをつくる
- 参考：[GitHub Docs - 個人アクセストークンを使用する](https://docs.github.com/ja/authentication/keeping-your-account-and-data-secure/creating-a-personal-access-token)
- 作成後にできる文字列をコピーしておく
2. SAKAZUKIレポジトリの設定のSecretsに、1で作ったToken（文字列）を「PAT」の名前で登録する
- SAKAZUKI→Settings→Secrets→New Repository Secret
- PRに自動でautofixしたコミットをつけてくれる/fixコマンドを実現した
- GitHub …
=> PR時にautofixをコメントでのコマンドでできるようにした

app/packs/entrypoints/devise.scss, app/packs/entrypoints/sakes/form.scss, app/packs/entrypoints/sakes/index.scss, app/packs/entrypoints/sakes/show.scss, app/views/devise/confirmations/new.html.erb, app/views/devise/invitations/edit.html.erb, app/views/devise/invitations/new.html.erb, app/views/devise/passwords/edit.html.erb, app/views/devise/passwords/new.html.erb, app/views/devise/registrations/edit.html.erb, app/views/devise/sessions/new.html.erb, app/views/devise/unlocks/new.html.erb, app/views/sakes/_form.html.erb, app/views/sakes/index.html.erb, app/views/sakes/show.html.erb
Close #322
rename後の名前がBootstrapのクラス（row、badgeとか）やHTMLセレクタ（labelとか）に被らないよう、元の名前を残しているものもある。
具体的にはこんな感じ。
`sakes-form-row` -> `form-row`
`sakes-form-label` -> `form-label`
`devise-row` -> `devise-row`
=> scssの`devise-`とか`sakes-form-`とかを消した

app/helpers/application_helper.rb, app/views/layouts/application.html.erb
fix #362 
めためた
display_meta_tagsの内容をset_meta_tagsやtitleで上書きができる。
しかしset_meta_tagsの内容はtitleで上書きしようとすると、順番依存が発生する。
- デフォルトのメタタグを作成した
- application.html.erbでは`display_meta_tags(default_meta_tags)`する
- `set_meta_tags`をまったく使わない！
- 各種ページで`set_meta_tags(...)`や`title`を使い設定を上書きする
=> Twitterでリンクサムネイルが壊れていた問題を修正

app/controllers/sakes_controller.rb, app/views/sakes/drink_menu.html.erb, config/routes.rb
お品書きをおしゃれに見せたいゾ！！！
プルリクが大きくなりそうなので分割したゾ。このプルリクは、oshinagakiブランチへのプルリクだゾ。
refer: [Sakazuki wiki-お品書き](https://github.com/momocus/sakazuki/wiki/%E3%81%8A%E5%93%81%E6%9B%B8%E3%81%8D)
- /sakes/drink_menu でお品書きページが表示されるよう、アクションとルーティングを追加した
- drink_menu.html.erbはアクションの確認用で、デザインはまだ
- 空のボトルは表示しない
- ページネーションはなしで、在庫はすべて表示する（indexのデフォルトに合わせる）
- 表示順はidソート（indexのデフォルトに合わせる）
=> Update: お品書きのルーティングとアクションを追加

app/controllers/sakes_controller.rb, app/models/sake.rb, app/packs/entrypoints/sakes/form.js, app/packs/src/typescript/sake_rating.ts, app/views/sakes/_form.html.erb, app/views/sakes/_rating.html.erb, app/views/sakes/show.html.erb, config/locales/models/sake.ja.yml, db/migrate/20220127072306_add_review_rating_to_sakes.rb, db/schema.rb, package.json, spec/factories/sakes.rb, spec/models/sake_spec.rb, spec/views/sakes/show.html.erb_spec.rb, yarn.lock
close #369
**db migrateが必要！**
好みの酒を記録できるぞ！！
- 酒モデルにratingカラムを追加
- 酒showページに☆で評価を表示
- 酒formで☆で評価を入力できる
- ☆入力にはrater-jsを使った
- rater-jsの☆をbootstrap-icon化
- bootstrap-iconsのstar.svgの読み込みがRails6だとやっかい
- Rails7化してから考える、Rails7でもやっかいかもしれない。
=> 酒の好みを評価できるようにした

Gemfile, Gemfile.lock, README.md, config/database.yml
fix #391
なんでもいいから`bundle exec parallel_rspec`だ！
手元では 55s → 35s くらい、6割くらいに削減できそう。
- 初回のみテストDBを複数個にするため`rake parallel:setup`をする
- `rspec`の代わりに`bundle exec parallel_rspec`を使う
- `rake parallel:drop`でコピーされたDBを削除できる
- `bundle exec rails db:create`でテストDBを1個だけ復元する
- parallel_tests gemを追加
- parallel_rspec向けに設定を更新
- README.mdを更新
- Github ActionsでのRSpecは並列化しなかった
- トラブルがあったときわかりくくなりそうな気がする。ピュアなテストにしておく。
=> RSpecを並列実行できるようにした

app/helpers/sakes_helper.rb, app/models/sake.rb, app/packs/entrypoints/sakes/drink_menu.js, app/packs/entrypoints/sakes/drink_menu.scss, app/views/sakes/drink_menu.html.erb, config/locales/views/sake.ja.yml, spec/helpers/sakes_helper_spec.rb, spec/models/sake_spec.rb, spec/rails_helper.rb
- お品書きのビューを追加した（テスト未）
- ビューで使う、下記二つのメソッドを追加した（テスト済）
- 酒一合当たりの値段を表示するための`selling_price`メソッド
- 酒が新着かどうかを判定する`new_arrival?`メソッド
https://github.com/momocus/sakazuki/wiki/%E3%81%8A%E5%93%81%E6%9B%B8%E3%81%8D
- **モバイル版のデザインを決める**
- お品書きのビューに対するテスト
- トップページからお品書きページへアクセスできるようリンクを貼る（ハンバーガーメニューに入れるつもり）
- リンクからアクセスできるかのテスト 
- ~~お品書きのビューのデザイン~~（モバイル版のデザインをちゃんと決めてなかったから、次のプルリクでやり直し）
- `selling_price`メソッドと`new_arrival?`メソッドのコード
=> お品書きビューを追加

.eslintrc.js, app/packs/src/typescript/input_taste_graph.ts, app/packs/src/typescript/show_taste_graph.ts, app/packs/src/typescript/taste_graph.ts, app/views/sakes/_form.html.erb, config/locales/views/sake.ja.yml
close #387 
ださいリセットボタンとおさらば、ratingとの統一感をとるぞ！
- 味香りグラフのリセットボタンを削除した
- 既存点クリックを味香りグラフのリセットにした
- こっそり味香りグラフのバグ修正
- 動作は問題なかった
- ESLintの設定を変え、TSの`_variable_name`の未使用を許可した
- 今まで設定済みと勘違いしていた
=> 味香りグラフのリセットを今までの別ボタンを止め既存点をクリックに変えた

app/views/layouts/_header.html.erb, spec/support/sign_in.rb, spec/views/layouts/_header.html.erb_spec.rb
ハンバーガーメニューに表示するリンクのテストを追加した（Fix #411）
どのユーザーにどのリンクを表示するかの表
|  link \ user               | non signed in | signed in & non admin | signed in & admin |
| --------------- | ------------- | --------------------- | ----------------- |
| sign in         | o             | x                     | x                 |
| sign out        | x             | o                     | o                 |
| elasticsearch   | o             | o                     | o                 |
| user edit       | x             | o                     | o                 |
| user invitation | x             | x                     | o                 |
o: 表示  x: 非表示
=> ハンバーガーメニューに表示するリンクのテスト

app/controllers/sakes_controller.rb, app/helpers/sakes_helper.rb, app/views/sakes/_form.html.erb, config/locales/views/sake.ja.yml, spec/helpers/sakes_helper_spec.rb, spec/rails_helper.rb, spec/system/sake_form_date_select_spec.rb
fix #403
見つからないPR 403
- 酒formの瓶詰め日、BYをRSpecで記述した
- BYを勝手に変えるバグを修正した
- BYはnil値を許可するため、nilのとき新規酒なのかnil BYの酒なのか判定を間違えていた
- ~~日本元号つきselect関数を大幅にリファクタした~~
- ~~これからは普通のformのようにclassやdata-testidを付加できるぞ！~~
- 自前select関数を使うのをやめ、Railsのselect/date_selectをなるべく使うようにした
=> BY不明の酒を編集してもちゃんとBY不明のままにした

Dockerfile, Gemfile, Gemfile.lock
Close #226
elasticsearch-railsのruby3対応バージョンがやっとリリースされたぞ！
=> Update: elasticsearch をruby3対応バージョンに上げた

app/views/sakes/_show_abstract.html.erb, package.json, spec/support/factory_bot.rb, spec/system/sake_show_simple_lightboxes_spec.rb
fix #434
node_modules/simplelightbox/dist/simple-lightbox.modules.jsにて、globalオブジェクトを前提としている。
globalオブジェクトはnode.jsで定義されるオブジェクトで、ブラウザではwindowオブジェクトとなる。
そのため、esbuildのオプションでglobalという名前でwindowオブジェクトを定義することで回避した。
後々はnode.jsのcommonJS前提が駆逐され、必要なくなるオプションかもしれない。
参考
https://developer.mozilla.org/ja/docs/Glossary/Global_object
https://github.com/evanw/esbuild/issues/73
=> Fix: Rails7環境でSimpleLightboxが動かない不具合を修正

app/views/kaminari/_gap.html.erb, app/views/kaminari/_next_page.html.erb, app/views/kaminari/_page.html.erb, app/views/kaminari/_paginator.html.erb, app/views/kaminari/_prev_page.html.erb, app/views/sakes/index.html.erb, config/initializers/kaminari_config.rb
fix #438
小さくはみ出さないページネーション
こっちにした
こっちは止めた
- kaminariのページ省略記号をbootstrap-icons化した
- kaminariのクリックできない3dotsや現在ページはtabでも反応させない
- 必要ないaタグのremoteを削除
- Issue #437 をしたときに復元する
- kaminariによるページネーションで最初・最終のページは1つだけ表示にした
- 「1 2 … 4 5 6 7 8…」を「1…4 5 6 7 8…」のようにした。
- 2っていらないじゃんと思った。
- ~~特に小さな画面では小型ページネーションを使う~~
- ~~上記対策でもiPhone SEのような小型画面でははみ出うるので。~~
- 小さな画面ではページネーションの表示数を減らす
=> 小さな画面でページネーションを小さくした

Gemfile, Gemfile.lock, app/helpers/application_helper.rb, app/javascript/application.js, app/views/layouts/application.html.erb, config/cable.yml, package.json, yarn.lock
fix #437
おめでとう、TurbolinksはTurboに進化した
- turboのインストール
- turboの設定を追加
- デフォルトでturboがオンなので、以前のTurbolinksのような`data-remote: true`は必要ない
- 不具合が起きたら`data-remote: false`でリンクのTurboをオフにできる
=> Turboを導入した

app/views/layouts/_header.html.erb, app/views/sakes/show.html.erb, spec/system/flash_message_spec.rb, spec/views/layouts/_header.html.erb_spec.rb
fix #454
ふらっっっしゅ！！！！
- ナビゲーションバーのViewにおけるtestidの振り方を変えた
- testidでリンクがクリックできないので、方法を変更
- flashメッセージが表示されるRSpecを書いた
- deviseの各種メッセージのテスト
- 例えば、「パスワードリセット」や「アカウントロックメール」やら、、、たくさん
- メッセージがでないと何をしているかわからないから結構致命的
- いつか書くべき？
=> FlashメッセージのRSpecを追加

spec/system/copy_sakes_spec.rb, spec/system/sake_form_bindume_date_spec.rb, spec/system/sake_form_bottle_level_spec.rb, spec/system/sake_form_completion_from_names_spec.rb, spec/system/sake_form_datetime_spec.rb, spec/system/sake_form_kura_completion_spec.rb, spec/system/sake_form_photos_spec.rb, spec/system/sake_show_simple_lightboxes_spec.rb, spec/system/sign_in_redirect_by_drinkbutton_spec.rb
酒のedit/newのような酒formに関するスペックは全部`sake_form_***`という名前にしておいた。
そのうちサブディレクトリ掘ってもいいよね。
=> 酒フォームに関するRSPecの名前を揃えた

app/assets/stylesheets/application.scss, app/views/layouts/_flashes.html.erb, app/views/sakes/_float-button.html.erb, app/views/sakes/_form.html.erb, config/application.rb, config/locales/views/sake.ja.yml, spec/support/capybara.rb, spec/system/copy_sakes_spec.rb, spec/system/drink_buttons_spec.rb, spec/system/edit_sake_spec.rb, spec/system/flash_message_spec.rb, spec/system/new_sake_spec.rb, spec/system/sake_form_bindume_date_spec.rb, spec/system/sake_form_bottle_level_spec.rb, spec/system/sake_form_datetime_spec.rb, spec/system/sake_form_photos_spec.rb, spec/system/sake_form_validation_spec.rb
close #463 
フラッシュメッセージを改変するのはやめだ。
Bootstrapに従うんだ！
サブミットボタンを押しても、画面遷移は行われない。
ブラウザが判定してメッセージを出す。
フォーム直下にエラーメッセージが表示される。
- HTML5のinput required属性を使って酒フォームの入力必須値を設定した
- 入力フォームエラーが起きたとき、フォーム直下にBootstrapのvalidationスタイルでエラー内容を表示する
- configを変更して、Railsの`field_with_errors`スタイル付加されたdivタグを作らないようにした
- 代わりに、Bootstrapの`is-invalid`をスタイルに追加する
- あとからだけど、テストも追加した！
- Deviseの複数エラーの対応はまだ → Issue #102
- Devコンソールを使わないと起こせないバリデーションエラーはエラー内容表示をしない
- 例えば香りの値の入力制限をわざわざ消してから"-1"にセットする、など
=> 酒フォームにてフラッシュメッセージでなくフォーム直下にエラー内容を表示するようにした

app/assets/stylesheets/application.scss, app/views/sakes/_drink-button.html.erb, app/views/sakes/_rating.html.erb, app/views/sakes/_show_review.html.erb, app/views/sakes/index.html.erb, spec/system/drink_buttons_spec.rb, spec/system/sign_in_redirect_by_drinkbutton_spec.rb
Issue #405 やる前の準備
- 酒indexの検索フォームをリファクタ
- rowの構成見直し
- data-testidの指定方法を揃えた
- 必要ないハッシュを削除
- 酒viewのrating内でのフォントサイズ指定を行わないようにした
- 他の箇所からもratingを呼び出すのに便利
- 必要ない@extendを削除した
- 1要素を別名保存しても意味ないね
- drink-buttonのtestidをアンダーバー化した
- 徐々にハイフン繋がりのtestidを駆逐していく
=> 酒indexのデザイン変更前のリファクタ

Gemfile.lock
Fix: #475
debug gemのバージョンを1.5.0に上げることで、macOS上のdocker環境でrails s や rails db:createで落ちる問題を解消。
=> Fix: #475 debug gemのバージョンを1.5.0に上げた

app/assets/stylesheets/sakes_index.scss, app/javascript/application.js, app/javascript/taste_graph/taste_graph.ts, app/views/sakes/_drink-button.html.erb, app/views/sakes/_form.html.erb, app/views/sakes/_show_review.html.erb, app/views/sakes/index.html.erb, config/locales/views/sake.ja.yml, spec/system/drink_buttons_spec.rb, spec/system/sign_in_redirect_by_drinkbutton_spec.rb, spec/views/sakes/index.html.erb_spec.rb
after #469
fix #405
ついに新たな酒indexとなったぞ！
- 酒indexを新たなデザインにした
- カードデザインを採用した
- 画面サイズによって3列・2列・1列が切り替わる
- グラフは4x3ですべて固定した
- 各種RSpecを修正した
- 構造が大きく変わったので、testidの振り方を修正
- 変更箇所のみリファクタ
=> 酒indexのデザインを新しくした！

app/uploaders/image_uploader.rb
fix #172
本当にこれでいいのかは怪しい。
- うまくいっているやつ
- 「しぼりたて」がきれいに認識されてるようだ
- https://github.com/momocus/sakazuki/issues/172#issuecomment-1082011589
- うまくいってないやつ
- フォントがおしゃれだとダメ
- https://github.com/momocus/sakazuki/issues/172#issuecomment-1077351333
- 無料枠なので月50回まで
- 1ヶ月に50本は消費しないだろという目論見
- 最悪ケースは、画像変換方式が変化してから過去ログを一気に見た場合。そのときはそのときで考えよう。
- 日本語指定を`adv_ocr:ja`で指定できるとあるけど、どこにつけるの？
- ドキュメントでは`upload`関数につけろというけど、CarrierWaveが`upload`をラップしているため直接指定できない
- `process`に指定したけど本当にこれでいいの？
- Cloudinaryドキュメント - 画像変換
- https://cloudinary.com/documentation/image_transformations
- Cloudinaryドキュメント - OCRテキストの検出と抽出
- https://cloudinary.com/documentation/ocr_text_detection_and_extraction_addon
=> Update: Twitterカード用画像をテキスト優先で切り抜くようにした

app/views/layouts/application.html.erb, app/views/sakes/_float-button.html.erb, app/views/sakes/_form-abstract.html.erb, app/views/sakes/_form-detail.html.erb, app/views/sakes/_form.html.erb, app/views/sakes/_show_abstract.html.erb, app/views/sakes/_show_detail.html.erb, app/views/sakes/_show_review.html.erb, app/views/sakes/edit.html.erb, app/views/sakes/index.html.erb, app/views/sakes/menu.html.erb, app/views/sakes/new.html.erb, app/views/sakes/show.html.erb
パーシャルビューでインスタンス変数を使うのはよくない！
- パーシャルビューでインスタンス変数を使っていた
- `@sake`を使える前提で書いている
- これだと、render呼び出しによってはインスタンス変数が存在しないというエラーになる
- 必要な変数はrenderの呼び出しからしっかり渡す！
- render呼び出し時に引数のハッシュキーを省略できなくなる
- 明示的でわかりやすい
- `render(partial: "PARTIAL_VIEW_NAME", locales: { VAR_NAME1: VALUE1, VAR_NAME2: VALUE2, ... })`
- パーシャルビューの呼び出し方法を変更
- ~~パーシャルビューの名前をハイフン区切りで揃えた~~
- 別Issueにした
=> パーシャルビューでインスタンス変数を使わない

Dockerfile
Closes #512
`libpq-dev=14.*` の段階で PostgreSQL server の 13系とはずれているわけですし、CI で動作確認できているのなら 15.* にあげてもいいのじゃないでしょうか
=> Fix missing libpq-dev=14.*

Gemfile.lock
Closes #513
今回は Apple Silicon (ARM系）の Mac でも sakazuki の Docker を実行できるように、
```
bundle lock --add-platform arm64-darwin
```
で platform を Gemfile.lock に追加しました。
これにともなって、arm64-darwin であれば事前にネイティブビルド済みの nokogiri がインストールされるようになったようです。
- M1 Mac + macOS 12 でのみ検証しました。
**_x86_64 の Linux や Windows では検証していませんので、ご確認ください。_** 
- `docker compose build` ⇨ `docker compose run` 
次のように Rails サーバーが無事立ち上がりました。
```
sakazuki-web-1  | => Booting Puma
sakazuki-web-1  | => Rails 7.0.2.2 application starting in development 
sakazuki-web-1  | => Run `bin/rails server --help` for more startup options
sakazuki-web-1  | Puma starting in single mode...
sakazuki-web-1  | * Puma version: 5.6.4 (ruby 3.1.1-p18) ("Birdie's Version")
sakazuki-web-1  | *  Min threads: 5
sakazuki-web-1  | *  Max threads: 5
sakazuki-web-1  | * …
```
=> Apple Silicon 向けビルド済み nokogiri がインストールされるようにする

.github/workflows/check.yml, .github/workflows/test.yml
close #516
Skip Duplicate Actionsというアクションを使って実現している。
ファイルの変更を見て同じテストやチェックをスキップできる。
PRの表示には重複して起動はするが、内容を見るとスキップされるようになり高速化が期待できる。
監視対象のファイルを細かく設定でき、よりスキップする場合を増やすこともできる。
ただ設定するコストと今後の管理コストの高さから今回は導入していない。
https://github.com/marketplace/actions/skip-duplicate-actions
=> 重複したActionsをスキップするようにした

.github/workflows/check.yml, Dockerfile, cli-scripts/run-all-checks.sh
heredoc書けるようになったよ！
- &&\地獄から抜けれる
- RUNをまとめてスッキリ書ける
- RUNをheredoc化
- apt installの順番を、基本コマンドとSAKAZUKI依存パッケージで分けた
- SAKAZUKI依存パッケージのapt installの順番をセットアップ順に揃えた
- aptのクリーニング作業を1つにまとめた
- nodeのバージョンを次期LTSの16にした
- 12もLTSだがすでにEOL、新しいLTS出たので更新した。
- https://www.docker.com/blog/introduction-to-heredocs-in-dockerfiles/
=> Dockerfileをheredoc対応した

.github/workflows/test.yml
fix #527
Test Actionsで使うUbuntuを一時的に20.04で固定した。
Ubuntu 22.04イメージにFirefoxがまだ入っていない。
FirefoxをインストールするPRがすでにあるため、入るまでの暫定対処。
=> ubuntu-latestにFirefoxがないためTest Actionsが終わらない問題の暫定対処

app/controllers/sakes_controller.rb, app/views/sakes/index.html.erb, spec/system/sake_index_order_spec.rb
close #520
after PR #519
- 酒indexで酒はid順にならんでいた
- 開封済み・未開封が混ざった順番でわかりずらい（Issue #492 でも言われていた）
- 瓶状態でのソートをデフォルトにしてみよう！
- Add: 酒indexでの酒の順番についてのテストを追加
- Update: 酒indexでの酒並び順を変更した
- Refactor: 変数名の命名をRansackのドキュメントに合わせた
=> 酒の並び順を瓶状態で並べるようにした

app/views/sakes/_drink_button.html.erb, config/locales/views/sake.ja.yml
close #495
after PR #543
- drink-buttonのメッセージ変更
- 「栓を開けます？」→「ほしいずみ 特別純米 無濾過生原酒 の栓を開ける？」
- 「飲みきった？」→「ほしいずみ 特別純米 無濾過生原酒 を飲みきった？」
=> drink_buttonの開封・空の操作時のメッセージに酒名をつけた

app/helpers/sakes_helper.rb, app/views/sakes/index.html.erb, spec/helpers/sakes_helper_spec.rb, spec/views/sakes/index.html.erb_spec.rb
close #541 
- 酒indexにおけるメタタグのタイトルの変更
- 酒の総量は含めないようにした
- 検索中のときは検索ワードを含めるようにした
- 酒indexのH1タイトルとメタタグタイトルのビューテストを追加
=> メタタグのタイトルに検索内容を含めるようにした

dev.Dockerfile
close #508
close #511
- ベースDockerイメージをbusterからbullseyeにあげた
- apt-keyをやめた
- keyringsは`/usr/share/keyrings/`まとめた
- 軽度なりファクタ
- Dockerfileにapt-get upgradeを追加した
- curlのオプションを揃えた
=> 開発環境DockerのDebianバージョンをbullseyeにあげた

README.md, app/uploaders/image_uploader.rb
Close https://github.com/momocus/sakazuki/issues/537
酒画像を.webpに変換してアップロードし、サイズが小さくなるようにした
本番環境でCloudinaryがどう動くかみようとしたらうっかり #558 がMergedになってしまったので、このプルリクを書いた。
=> 画像アップロード時にサイズを小さくして容量節約

app/javascript/autocompletion/complete_detail.ts, app/javascript/autocompletion/detail_dicts.ts, app/javascript/sakes_form.js, app/views/sakes/_form_detail.html.erb, config/locales/models/sake.ja.yml, spec/system/sake_form_completion_for_detail_spec.rb, spec/system/sake_form_completion_for_kura_and_todofuken_spec.rb
close #379
これが欲しかった
- 酒の”しぼり”のtypo修正（絞り→搾り）
- 酒フォームでなぜか残っていた「火入れ状態」から状態を削除
- 名前からの酒情報補完機能のテストを追加
- 合わせて、蔵・都道府県の補完機能のスペック名を変更
- 酒の名前から詳細情報などを補完する機能を実装した
- 補完される項目は、特定名称、季節、酛、搾り、ろ過、火入れ、加水。
=> 酒タイトルから酒情報を補完する

app/controllers/sakes_controller.rb, app/models/sake.rb, app/views/sakes/_form_abstract.html.erb, app/views/sakes/_sake.json.jbuilder, app/views/sakes/_show_abstract.html.erb, config/locales/models/sake.ja.yml, db/migrate/20230216073620_rename_date_columns.rb, db/schema.rb, spec/factories/sakes.rb, spec/models/sake_spec.rb, spec/system/copy_sakes_spec.rb, spec/system/sake_form_bindume_date_spec.rb, spec/system/sake_form_brewery_year_spec.rb
close #402
**`rails db:migrate`が必要！**
- DBカラム名を変更するマイグレーションを作成
- bindume_date -> bindume_on
- brew_year -> brewery_year
- マイグレーション`rails db:migrate`の実行
- カラム名の変更に合わせて既存変数やファイル名を変更
=> 酒のDate型カラムをRailsの命名規則に合わせた

app/views/sakes/_sake.html.erb, config/locales/views/sake.ja.yml
close #492
わからん、運用してみないことには。
- 酒indexの画像とグラフの位置と大きさを変更
- グラフとレビューは近いほうがよい。
- 酒indexにおける瓶状態のフォーマットを変えた
- 「1ヶ月前に開封」から「未開封 - 1ヶ月前」にした
- 瓶状態の位置がすべてのカードで揃うので、より瓶状態が見やすくなることを狙う
- 後ろの1ヶ月前などは`muted`で薄くしている
- READMEに貼るスクリーンショットの更新
- レビュー通ってからやる
=> 酒カードのフォーマットを変更した

app/assets/stylesheets/sakes_index.scss, app/javascript/sakes_index.js, app/views/sakes/_sake.html.erb, spec/support/factory_bot.rb, spec/system/sake_show_simple_lightboxes_spec.rb, spec/views/sakes/index.html.erb_spec.rb
close #488
~~after #571~~
~~conflict with #573~~
- 酒indexの酒画像の拡大表示ができることのviewテストを追加
- 酒indexの画像をSimpleLightboxで拡大表示できるようにした
=> 酒indexでも画像を拡大表示できるようにした

.github/workflows/check.yml, .github/workflows/test.yml, fly.Dockerfile
小さなミスを何個か見つけちった
- fly.io向けコンテナのyarnとbundleでproduction環境を使うようにした
- 今まで無駄なファイルがデプロイされていた気がする
- 動かしてみないと正しいかわからない
- Actionsで必要ないbundle installを削除
- ruby/setup-ruby@v1がやってくれるので必要なかった
- Test Actionでの無駄な`yanr install`を削除
- `yarn workspaces focus --all --production`だけでよく、その後の`yarn install`は余計だった
- Test Actionで必要ないtest環境指定を削除
- rspecはrailsじゃないので`RAILS_ENV=test`は必要ない
- Test Actionでbundle環境にtest環境を指定した
- ruby/setup-ruby@v1で指定したbundleのtest環境指定は、bundleコマンドを使う各種で指定する
=> flyとActionsのコンテナ環境の指定間違いを修正

app/assets/stylesheets/sakes_form.scss, app/controllers/sakes_controller.rb, app/helpers/sakes_helper.rb, app/views/sakes/_form_abstract.html.erb, config/locales/models/sake.ja.yml, spec/helpers/sakes_helper_spec.rb, spec/system/copy_sakes_spec.rb, spec/system/sake_form_bindume_date_spec.rb
close #477
after #555
我々が本当にほしかったもの
- 酒formにおける製造年月の入力を年・月別々のセレクタから1つのセレクタにした
- 酒のアトリビュートの翻訳を「製造年月日」から「製造年月」に変更
- 日なんて概念なかった
- 酒フォームの製造年月の実装に合わせて、BYもリファクタ
- めちゃくちゃスッキリした
- フォームが変わったのに伴い、関連テストを修正
=> 酒フォームで製造年月の年と月を1つのセレクタで選ぶようにした

.github/workflows/check.yml, .github/workflows/codeql.yml, .github/workflows/fix-command.yml, .github/workflows/test.yml
close #582
- CodeQLのv1からv2にあげた
- すでにv1は2023/01/18でdeprecatedになっている。
- ここにあるように、1文字を2箇所変えただけ
- https://github.blog/changelog/2023-01-18-code-scanning-codeql-action-v1-is-now-deprecated/
- checktout/cache actionをv2からv3にあげた
- ここにあるように、1文字を何箇所か変えただけ
- https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#example-using-versioned-actions
- ~~`::set-output`を使わないようにした~~
- ~~新たな`GITHUB_OUTPUT`を使って書き直した~~
- https://docs.github.com/en/actions/using-workflows/workflow-commands-for-github-actions#environment-files
- ~~キャッシュヒット失敗したときにパッケージ一覧を出すようにした~~
- ~~公式Docでやってて、デバッグに便利そう~~
- ~~https://docs.github.com/ja/actions/using-workflows/caching-dependencies-to-speed-up-workflows~~
- お手性キャッシュをやめて、actions/setup-nodeを使ってキャッシュ処理するようにした
- https://github.com/actions/setup-node
- …
=> 👓 GitHub Actionsの複数の警告を解消した

.rubocop.yml
Rubocopを実行すると下記のようなメッセージが出ていた。
いつの間にか、新たなrubocop-capybara gemが入っているようである。
メッセージに従い、有効化した。
```console
)$ rubocop
Inspecting 90 files
..........................................................................................
90 files inspected, no offenses detected
The following RuboCop extension libraries are installed but not loaded in config:
* rubocop-capybara
You can opt out of this message by adding the following to your config (see https://docs.rubocop.org/rubocop/extensions.html#extension-suggestions for more options):
AllCops:
SuggestExtensions: false
```
- https://docs.rubocop.org/rubocop-capybara/cops_capybara.html
=> Add: 新たなrubocop-capybaraを有効化した

.eslintrc.json, package.json
close #599
- 警告はESLintがエラーせずに終わる
- 必要ない`eslint-disable`コメントのチェックが抜けていた
- 消し忘れたeslint-disableコメントを警告にした
- eslintの警告を1個以上でexit 1するようにした
- 細かなリファクタ
- JS/TSの構文バージョンを最新に指定
- 空のplugin項目を削除
- 必要ない配列表記を削除
=> ESLintに新たなエラー設定を増やした

app/controllers/sakes_controller.rb, app/models/sake.rb, db/migrate/20230325130307_change_sakes_default.rb, db/schema.rb, spec/factories/sakes.rb, spec/models/sake_spec.rb
- Controllerに定義されていた下記カラムの初期化処理を、Migrationに定義した
- size
- Migrationに定義されていた下記カラムの初期化処理を、Sakeモデルに移した。
- opened_at
- emptied_at 
- Controllerに定義されていた下記カラムの初期化処理を、Sakeモデルに移した。
- bindume_on
- Controller定義されているbrewery_yearの初期化処理を、Sakeモデルに移せてない。
- to_byメソッドをSakeモデルに移動することになりそうなので、#594 もかかわってくる。
関連：#611 #594
=> 一部の初期化処理のリファクタ

README.md, docker-compose.yml, dotenv.example, spec/support/capybara.rb
Close #202
やったこと
docker compose上でrspecを実行する時、リモートのfirefoxブラウザを使ってブラウザテストをできるようにした。
やってないこと
docker composeを使わずにdockerコンテナで動かすときは、リモートのfirefoxブラウザを使わない（今まで通りローカルのfirefoxを使おうとする）
=> Update: docker compose上でブラウザテストできるようにした

app/views/kaminari/_next_page.html.erb, app/views/kaminari/_page.html.erb, app/views/kaminari/_prev_page.html.erb, app/views/sakes/index.html.erb
**feature-hotwireへのマージ**
超高速なページネーションを！
- （復習）Turbo Driveは、ページのbodyのみを書き換えることで高速化していた
- Turbo Frameは任意のフレーム（実際にはHTMLタグ1つ）のみを書き換えることでより高速化する。
- SAKAZUKIでいうと、indexページの酒の一覧表示の更新をTurbo Frame化することで高速化できる。
- indexページの酒カードが並ぶ箇所をTurbo Frame化
- ページネーションによる遷移でTurbo Frameを利用
- 検索による遷移でTurbo Frameを利用
- 空き瓶表示におけるチェックボックスによる遷移でTurbo Frameを利用する
- チェックボックスはJSで更新を発火させており、Turbo Frame化が複雑と思われる
- チェックボックスで遷移すると、Turbo Frame外の更新がいるためTurbo Frame利用できない
- 具体的には、H1タグの酒総量の更新もいるため。デザイン変更が必要。
=> ページネーションの動作にTurbo Frameを導入した

package.json, tsconfig.json, yarn.lock
close #622 
TypeScriptのバージョンアップ！
- Typescriptをv5にあげた
- ESLintのプラグインのtypescript用parserもバージョンアップ
- tsconfigのモジュール解決に新たな設定値bundlerを指定した
- https://devblogs.microsoft.com/typescript/announcing-typescript-5-0/#moduleresolution-bundler
- https://blog.s2n.tech/articles/dont-use-moduleresolution-node
- このブログに刺激を受けてパッチ書いた
=> 🌟 Typescript5

cli-scripts/export_kura.rb, cli-scripts/export_meigara.rb, cli-scripts/export_sakamai.rb, cli-scripts/get_kura.rb, cli-scripts/get_sakamai.rb
fix #624 
これでどこからでも呼び出せるわ！
例えば、
- `./cli-script/export_kura.rb`
- `cd ./cli-script && ./export_kura.rb`
のどちらも正しく動くようにした！
=> Fix: Rubyスクリプトを実行パスに依存しないようにした

fly.Dockerfile
すでに環境変数BUNDLE_WITHOUTを設定してある。
そのため、bundle configで改めて設定する必要はない。
- Bundler - bundle config
- https://bundler.io/v2.4/man/bundle-config.1.html#CONFIGURATION-KEYS
=> Refactor: 必要ないbundle configを削除

.eslintrc.json, app/javascript/taste_graph/input_taste_graph.ts, app/javascript/taste_graph/show_taste_graph.ts, app/javascript/taste_graph/taste_graph.ts, tsconfig.json
close #626 
after #623 
型のインポートには明示的な構文を使おう！
- 型をimportするのに`import type`を使うの強制できる
- tscのチェックでエラーが起こる
- 関数と型のどちらを読み込んだのか、importの構文で明示できる！
```typescript
import type { TypeName } from "module" // eslint --fixによるオートフィクスはこの形になる
import { type TypeName, ClassName } from "module"
import type * as t from "module"
```
```typescript
import { TyepName } from "module"
```
```console
$ yarn lint:tsc
hogehoge.ts:1:10 - error TS1484: 'TypeName' is a type and must be imported using a type-only import when 'verbatimModuleSyntax' is enabled.
1 import { TypeName } from "./module"
```
- Update: 新たなオプションverbatimModuleSyntaxをオンにした
- 合わせて、対応するESLintのルールをオンにした
- これがあると、`eslint --fix`で自動修正もできるので便利
- https://typescript-eslint.io/rules/consistent-type-imports/
- Refactor: 型のインポートにimport typeを使うようにした
=> TypeScriptのverbatime module syntaxオプションをオンにした

app/javascript/taste_graph/taste_graph.ts
fix #636
味香りグラフで一番左下の(-3,-3)を入力すると、
グラフ上は描画できているが、Railsでのデータが(null,null)になっていた。
正しくは、Railsで(0,0)の値がDBに登録されてほしい。
問題は、or条件で0が誤判定されているのが原因だった。
この条件式を書き直すことで修正。
こういったテストの導入はまだ行っていない。
JUnitのようなJS/TSのテストや、ブラウザサイズ固定のfeatureテストが必要かも。
=> Fix: 味香りグラフで0を入力できない不具合を修正

docker-compose.yml
Close #608
publicをバインドマウントして、画像が残るようになった。
=> fix: docker composeを立ち上げなおすと画像が消える #608

.eslintrc.json, app/javascript/simple_lightbox/simplelightbox.d.ts, app/javascript/taste_graph/taste_graph.ts
覚悟を決めろ！
- typescript-eslintのstrictをオンにした
- TypeScriptにてinterfaceよりもtypeを優先的に使うようESLintに設定した
- 設定変更に伴う修正
=> typescript-eslintのstrictをオンにした

.github/auto_assign_configs.yml, .github/workflows/auto-assign.yml
close #658
- Auto Assign Actionを導入した
- PRにレビュアーと担当者が自動で割り当てられる
- レビュアーはmomocusとyontaを指定した
- 担当者はPR作成者とした
- フォークレポジトリからのPRとdepended botのPRには担当者を自動付けしていない
- ドキュメントにある通り、条件を`pull_request_target`にすればできる
- とはいえフォークPRでActionsを動かせるため、セキュリティリスクが起こりうる、とドキュメントにも書いてある
- 第三者からのPR少ないし、とりあえずオフでいいかなと
- https://github.com/marketplace/actions/auto-assign-action
=> Update: PR時に自動でレビュアー・アサイニーを登録するようにした

app/views/layouts/application.html.erb, spec/views/layouts/application.html.erb_spec.rb
close #669
- Test/Prod環境でレターオープナーへのリンクがないテストを追加
- letter_openerへのリンクを、下部のデバッグ情報に追加
=> letter_openerへのリンクをdev環境で追加

.eslintrc.json, app/javascript/controllers/input_taste_graph_controller.ts, app/javascript/controllers/show_taste_graph_controller.ts, app/javascript/taste_graph/taste_graph.ts, package.json, yarn.lock
close #640
ちゃんとTypeScriptでもドキュメントを書くぞ！
- eslint-plugin-jsodcを導入した
- 使いやすいようにJSDocの設定を調整した
- 不足していたTSDocを書いた
- TSDocが書きやすいようにTasteGraphコンストラクタの型を変更した
- TSDocが書きやすいほうが、コンストラクタも使いやすいと思う
- 実際、TSDocに従ったらバグも見つけてしまった。
=> TSDocを必須とした

.eslintrc.json, app/javascript/controllers/sake_name_controller.ts, package.json, yarn.lock
close #641
- typescript-eslintのバージョンをv6系にあげた
- typescript-eslint v6系に合わせた設定に変更
- ESLintの指摘を修正
=> typescript-eslintをv6系にあげた

dev.Dockerfile, fly.Dockerfile
fix #688
- 存在しない`.yarn/plugins`のCOPY節をDockerファイルから削除
=> Remove: すでに存在しない.yarn/plugins/のコピーをDockerfileたちから削除

app/models/photo.rb, app/views/sakes/_sake.html.erb, app/views/sakes/_show_abstract.html.erb
fix #679 
- Production環境におけるCloudinaryの画像URLに`a_ignore`を含めるようにした
- 既存DBのURLにはバージョン情報が含まれており、このままでは画像変換が動かない
- バージョン情報が含まれない`public_full_id`を使うようにした
- `full_public_id`（isvrjjmhbqaahkz59avgのような画像を表すID）
- `cl_image_path`を`angle: :ignore`つきで呼び出し、`a_ignore`が含まれたURLを生成するようにした
- Development/Test環境では今まで通り、DBの画像URLを使うようにした
- `/public/upload/.../sake.jpg`（Railsルートからのパス）
- `cl_image_path`等での`angle: :ignore`のような変換オプションは無視される
- 画像の参照を取得する共通処理を、Photoモデルのメソッドにした
- 同じ処理が酒のindex/showの二箇所で使われていた
=> Fix: CloudinaryのAVIF画像が間違った横向きになるのを修正

app/views/sakes/_sake.html.erb, app/views/sakes/index.html.erb, spec/factories/photos.rb, spec/models/photo_spec.rb, spec/support/factory_bot.rb, spec/system/simple_lightboxes_spec.rb
fix #683
変更前はSimpleLightboxを呼び出すdata-controllerが複数存在していた。
そのため、StimulusがSimpleLightboxを複数回起動していた。
data-controllerを1つにしたため、正しくSimpleLightboxが1つだけ呼び出されるようにした。
=> Fix: 酒indexページでSimpleLightboxが重複して起動する不具合を修正

app/views/sakes/_show_abstract.html.erb
close #692
- シェア対象の文字列から、いらないスペースや改行を削除
=> Fix: シェアボタン用テキストにいらないスペースや改行が入っていたのを修正

app/javascript/taste_graph/taste_graph.ts, tsconfig.json
より安全な配列アクセス！
- noUncheckedIndexAcessをオンにした
- 新ルールでのtscチェックのエラーを修正
=> TSのnoUncheckedIndexAccessを有効化

fly.toml, lib/tasks/fly.rake
fix #713
- swapの設定をrake taskからfly.tomlに移動した
- 自分でswapファイルを生成する方法はすでに古いようだ
- 現在のドキュメントだと、fly.tomlに記述するとスワップを生成してくれる。
- https://fly.io/docs/reference/configuration/#swap_size_mb-option
- rake taskの依存関係を、rake taskらしい記法にした
- 参考：https://qiita.com/Teach/items/858cc7fcd29cf68d6e16
=> Flyデプロイでスワップファイルの生成に失敗するのを修正

.github/workflows/esbuild-bundle-analyzer.yml, package.json
fix #717
- たつのさんのesbuild-bundle-analyzerを導入した
- esbuildのbundleサイズをコメントで出してくれるすごいやつ
- 急に増えるのを監視したり、bundle最適化の効果だったりがわかるぞい。
- 上記Action用にpackage.jsonにスクリプトを追加
- esbuild時にmetafileを書き出すスクリプト
- https://esbuild.github.io/api/#metafile
- esbuild v0.20系になるとCLIじゃなくてJSで書かないといけないかも？
=> esbuild-bundle-analyzerのGithubActionを導入した

fly.Dockerfile
fix #719
- flyデプロイに使うイメージのOSバージョンを指定なしからbullseyeに明示した
=> Update: flyで使うイメージのOSバージョンをbullseyeに固定した

fly.Dockerfile
**hotfix!!!**
fix #728 
- Flyで使うイメージ名のtypoの修正
=> Fix: FlyデプロイのOS名のtypoを修正

app/assets/stylesheets/application.scss, app/views/layouts/application.html.erb, app/views/sakes/_sake.html.erb
close #690
- Fix: typo
- Fix: 酒カードの三点メニューボタンがキーボードフォーカス時にフォーカスリングがでないのを修正
- ![image](https://github.com/momocus/sakazuki/assets/849256/e904f5dd-753a-4f2f-9b8c-2a4b199bd69a)
- Fix: float-buttonがキーボードフォーカス時にフォーカスリングがでないのを修正
- float-buttonのshadowクラス適用をやめた
- focus-ringとshadowクラスは同じCSSのbox-shadowを使っているので干渉するのは仕様
- https://github.com/twbs/bootstrap/issues/39668
- ![image](https://github.com/momocus/sakazuki/assets/849256/7ee89602-09d8-4625-aa68-dbfbe3e7fc67)
=> キーボードによるフォーカスリングの問題を修正

.gitattributes
便利になるよ！
- .gitattributesファイルを追加した
- 自動生成ファイルのリストを追加した。
- これより、GitHubのdiff表示において、自動生成ファイルの内容は自動で折りたたまれる。
- 自動生成ファイル以外のattributesの設定
- ドキュメント
- https://git-scm.com/docs/gitattributes
- 他にできるらしいこと
- 改行コードの指定
- gitアーカイブ時の無視ファイル
- バイナリファイルの指定
- 特定ファイルのdiff/merge方法の指定
- 今は必要なさそう
=> Add: .gitattributesファイルを追加

.github/workflows/esbuild-bundle-analyzer.yml
GitHub Action のセキュリティ上の制限として、fork からプルリクに対する `pull_request` イベントでは、`GITHUB_TOKEN` に `pull-request` scope への write 権限が付与されません。
> https://docs.github.com/ja/actions/security-guides/automatic-token-authentication
> <img width="740" alt="image" src="https://github.com/momocus/sakazuki/assets/127635/b749d889-d077-438d-b79c-66304f9a77ce">
> ...
> [pull_request_target](https://docs.github.com/ja/actions/using-workflows/events-that-trigger-workflows#pull_request_target) イベントによってワークフローがトリガーされると、パブリック フォークからトリガーされた場合でも、GITHUB_TOKEN にはリポジトリの読み取り/書き込みアクセス許可が付与されます。 詳しくは、「[ワークフローをトリガーするイベント](https://docs.github.com/ja/actions/using-workflows/events-that-trigger-workflows#pull_request_target)」を参照してください。
esbuild-bundle-analyzer は pull-request にコメントを書き込むため、write 権限が必要です。
fork からのプルリクでも `GITHUB_TOKEN` に …
=> ci: fork から PR が来たとき esbuild-bundle-analyzer がコケるのを修正

app/javascript/controllers/add_tax_controller.js, app/javascript/controllers/add_tax_controller.ts, app/javascript/controllers/index.js, app/views/sakes/_form_abstract.html.erb, config/locales/views/sake.ja.yml, spec/system/sake_form_add_tax_spec.rb
close #723
レシートは税抜きの場合と税込みの場合があるぞ！
- 税込みボタンのテストを追加
- 酒の編集フォームに、税込みボタンを追加
=> 消費税込みボタンの追加

.github/workflows/check.yml, .github/workflows/codeql.yml, .github/workflows/fly.yml, .github/workflows/test.yml
fix #615 
- pushトリガーでのActions起動を削除した
- そもそも必要ない
- マージキュー化で邪魔なので削除
- ついでにこれにより入れていたskip-duplicate-actionsも削除した
- ~~FlyへのデプロイをGitHubマージキューで行うようにした~~
- Actionsのconccurency設定をして、Flyへのデプロイを同時に1つまでに制限した
- ちょっとしたリファクタ
- GitHub Actions doc
- https://docs.github.com/ja/actions/using-jobs/using-concurrency
- Fly doc
- https://fly.io/docs/app-guides/continuous-deployment-with-github-actions/
1. ベースブランチの保護ルールで「マージキューを必須にする」
5. マージの制限、の、マージする pull request の最大数、を「1」にする
6. 他はデフォルトでよさそう？たぶん
- レポジトリオーナーのももかすにしかできない
- ドキュメント
- https://docs.github.com/ja/repositories/configuring-branches-and-merges-in-your-repository/configuring-pull-request-merges/managing-a-merge-queue#managing-a-merge-queue
- 「Merge pull request」ボタンが「Merge when ready」ボタンに変わるらしい！
- ドキュメント
- …
=> Fly Deploy並列実行による失敗をマージキューで防ぐ

app/assets/stylesheets/application.scss, app/views/sakes/_show_review.html.erb
fix #741
酒ノートで改行がちゃんと表示できるよ！やったね！
- 酒ビューのtext要素（味・香り・ノート）で、改行を正しく表示できるようにした
- 酒ビューでテキストボックスのスタイルクラスに名前をつけた
- 無名divを使ったよんたってやつが悪い！
=> 酒ビューの味・香り・ノートで改行を表示できない不具合を修正

.github/workflows/esbuild-bundle-analyzer.yml
fix #736
- mainへのpushをトリガーに追加
- これがないから、比較元であるベースブランチの解析結果がからっぽだった。なので常に全部Addedだった！（はず）
- 一部のリファクタ
- actionsのバージョンアップ
- コメントやパーミッション設定を、公式ドキュメント通りにした
=> esbuild-bundle-analyzerが正しくファイルを認識するようにした

app/views/sakes/_form_review.html.erb, app/views/sakes/_show_review.html.erb, config/locales/views/sake.ja.yml
close #742
- 酒ビューにて炭酸の文字列が空のとき炭酸なしと補完するのをやめた
- 酒フォームの炭酸項目に選択肢を追加した
=> まだレビューされてない酒がすべて炭酸なしになるのを修正

Procfile.dev, dotenv.example
新規環境で苦労したのでドキュメント追加した
- **Add: Procfile.devにFirefoxコンテナを使う場合のコマンド例を追加**
- **Update: dotenv.exampleにてCapybaraの設定値を用途に応じて分けた**
=> FirefoxをDockerコンテナで実行するときのドキュメントを追加

dev.Dockerfile, fly.Dockerfile
fix #753
いつの間にかdocker開発環境が壊れていた！
- docker compose buildでビルド失敗するのを修正
- libpq-devのバージョン指定に問題があった
- Dockerfileにおけるリファクタ
- apt-getオプションを-qqから-qにした
- Yarnのバージョンを正しく指定した
=> docker compose buildが失敗するのを修正

.dockerignore, .github/workflows/fly.yml, Gemfile, README.md, dev.Dockerfile, docker-compose.yml, fly.Dockerfile
fix #752 
after #727 #754 
- docker compose開発で使うDockerfileでのRubyバージョン指定を変更
- コマンドが`docker compose build` -> `docker compose build --build-arg RUBY_VERSION=$(cat .ruby-version)`になった
- READMEにも記載
- dockerignoreに`.ruby-version`を追加
- fly deploy actionでのRubyバージョン指定を変更
- 新たにDetect ruby versionというstepを追加
- GemfileでのRubyバージョン指定を変更
- READMEでのRubyバージョン表記を「See .ruby-version file」にした
=> Rubyのバージョン指定を.ruby-versionのみで行うようまとめた

app/views/sakes/_form.html.erb, app/views/sakes/_form_note.html.erb, app/views/sakes/_form_review.html.erb, app/views/sakes/_show_note.html.erb, app/views/sakes/_show_review.html.erb, app/views/sakes/show.html.erb, config/locales/views/sake.ja.yml
after PR #747 
close Issue #748 
- 酒ビュー・フォームのノートを別フィールドセットにした
=> レビュー項にあった酒ノートを、新たな項にした

.github/dependabot.yml
dependabotには3つ機能がある。
1. 脆弱性のセキュリティ通知
2. 脆弱性対応のPRの自動生成
3. パッケージマネージャによるパッケージアップデートのPRの自動作成
レポジトリの設定のみで1と2は有効かされている。
実は3はレポジトリの設定＋設定ファイル`dependabot.yml`が必要。
今までは設定ファイルがないため3は動いていなかった。
- `.github/dependabot.yml`を追加
- パッケージアップデートは頻繁にくるので、うざったいようならオフにするのもあり。
- 生のBundler/Yarnを利用しているが、Dockerやdevcontainerを利用してのアップデート通知もある。
- 今後devcontainerを用意できたら移行できるとよりよい
- https://docs.github.com/ja/code-security/dependabot/ecosystems-supported-by-dependabot/supported-ecosystems-and-repositories
- https://zenn.dev/camomile_cafe/articles/52d8e641ba732d
- https://qiita.com/yokawasa/items/38c6a4242cbe0fd5bbf0
=> Dependabotがパッケージアップデート通知を行うための設定ファイルを追加

package.json, yarn.lock
fix #788
`yarn stylelint --version`で起動すらできなかった。
Nodeモジュールのロードに失敗している。
v16.1.0 -> v16.10.0にアップデートで治った
=> Fix: stylelintが起動できないのを修正

.github/workflows/test.yml
PR #801 を修正しているときに、Testワークフローが落ちていたのを修正。
- ubuntu-latestがUbuntu24.04になり、ImageMagickがインストールされてなくてテストが失敗するのを修正
- 一部ワークフローのタイトルを微修正
=> GitHub ActionsでImageMagickがないためテストが失敗するのを修正

.github/workflows/check.yml, cli-scripts/run-all-checks.sh
build時の引数RUBY_VERSIONを指定していないためエラーになっていた。
build checks時に引数を与えるようにした。
PR #759 とPR #755 の複合でエラーするようになった。
=> Fix: docker build checksが常に失敗するのを修正

app/helpers/sakes_helper.rb, app/views/sakes/index.html.erb, config/locales/views/sake.ja.yml, spec/helpers/sakes_helper_spec.rb, spec/views/sakes/index.html.erb_spec.rb
close #766 
- 酒indexで検索時のページタイトルとヘッダに検索情報を付加
- TurboFrameの範囲を拡大
- 上記検索情報があるページタイトルもTurboFrameに含めるようにした
- テストを追加・更新
=> 検索中のページタイトル・ヘッダーに検索情報を付加した

app/javascript/controllers/index.js, app/javascript/controllers/sake_size_controller.js, app/javascript/controllers/sake_size_controller.ts, app/views/sakes/_form_abstract.html.erb, app/views/sakes/_show_abstract.html.erb, config/locales/views/sake.ja.yml, spec/system/copy_sakes_spec.rb, spec/system/sake_form_size_spec.rb, spec/system/sake_form_validation_spec.rb
close #804 
酒サイズを選択性に！
そんなに数も多くないので、セレクトフォームよりもラジオインプットで実装した。
- 酒の内容量を自由入力欄からラジオボタンで選ぶようにした
- ラジオボタンのみが見えている
- 内部では隠しinputがありTSで同期している
- 選択肢その他で自由入力欄も用意した
- テストを追加
- 既存酒サイズに関するテストを調整
=> 酒のサイズをradioボタンで選択性にした

README.md, dev.Dockerfile, docker-compose.yml, fly.Dockerfile
fix #821
- dev.Dockerfileで使うlibpq-devのバージョンを正しく指定した
- DockerfileのSHELLオプションに-eを追加し、heredoc内スクリプト失敗時にエラー停止するようにした
- dev.Dockerfileのsyntaxバージョン指定を1.4 -> 1に変更
- 昔はheredocを使うために1.4指定が必要だったが、今は必要ない
- dev.Dockerfileにおけるpostgresql/yarn/nodeのインストールを分割した
- 今まではインストールエラー時にどのインストールでエラーしたかわからなかった
- どれがエラーしたかわかりやすい！
- dev.Dockerfileにおけるgem installの2行を1行にまとめた
- docker build checkの修正に伴い、docker compose buildをオプションなしで動くようにした
=> docker compose buildの失敗するのを修正

.rubocop.yml, Gemfile, Gemfile.lock, app/controllers/sakes_controller.rb, app/helpers/sakes_helper.rb, cli-scripts/export_meigara.rb, cli-scripts/get_kura.rb, cli-scripts/get_sakamai.rb, spec/system/copy_sakes_spec.rb
**featureブランチへのマージ！**
- rubocop-performanceを導入
- rubocopでオートコレクト、手動修正をした
=> Rubocop Performanceを追加

.rubocop.yml, spec/helpers/sakes_helper_spec.rb, spec/models/sake_spec.rb, spec/system/copy_sakes_spec.rb, spec/system/drink_buttons_spec.rb, spec/system/sake_form_completion_for_detail_spec.rb, spec/system/sake_index_order_spec.rb
**featureブランチへのマージ**
- 必要ない冗長な括弧設定を削除
- RSpecのcontextで使える接頭辞の制限を強めた
=> Rubocopの設定を一部変更

app/assets/stylesheets/application.scss, app/controllers/sakes_controller.rb, app/views/sakes/_menu_one_drink.html.erb, app/views/sakes/menu.html.erb
Close #834 
- お品書きに画像を追加
- 新着アイコンは酒名の先頭に
- デザインをよしなに
=> update: お品書きに画像を追加、他

.github/dependabot.yml, .github/workflows/auto-assign.yml, .github/workflows/check.yml, .github/workflows/esbuild-bundle-analyzer.yml, .github/workflows/fix-command.yml, .github/workflows/fly.yml, .github/workflows/slash-command-dispatch.yml, .github/workflows/test.yml
close #927 
- サードパーティー製ActionsをSHA指定にした
- DependaBotのアップデート対象にActionsを追加
- たつのさんが言ってた、SHAをDependaBotがアップデートできるか、SHAとタグバージョンの関係を表示してくれるか、不明
- 運用しながら見ていこう
=> サードパーティー製Actionsをタグ指定からSHA指定にした

app/assets/stylesheets/application.scss
close #973
絵文字バツは色が変更できない！
- バツを色つき絵文字から色なし記号に変更した
- 太さを指定した
=> 酒編集画面の削除バツ記号の色をdanger色にした

.github/workflows/test.yml, README.md, app/uploaders/image_uploader.rb, dev.Dockerfile
close #944 
[メモリ消費も少なく速度も早いVipsへ！](https://github.com/libvips/libvips/wiki/Speed-and-memory-use)
- **Update: ImageMagickからlibvipsに移行した**
- **Update: READMEの要件をImageMagickからlibvipsに変更**
- **Update: dev環境DockerfileをImageMagick -> libvipsにした**
- **Remove: ActionsのテストからImageMagickを削除**
=> ImageMagickからVipsへ移行

.github/workflows/test.yml
after #928
**オーナーによるレポジトリ設定の変更が必要！！**
- Codecovをv5にアップデート
- GitHubの仕様変更？によりTOKENが必要に
- v4はトークン無しは不可になった。
- v5はトークン無しでも手段はある
- トークンありの場合
- Usageにあるように、Actionsで指定する
- https://github.com/codecov/codecov-action?tab=readme-ov-file#usage
- レポジトリ設定でトークンを設定する
- https://docs.codecov.com/docs/codecov-tokens#example-github-actions--official-codecov-action
- トークンなしの場合
- 組織のトークン認証をオフにしているとできるらしい
- https://docs.codecov.com/docs/codecov-tokens#uploading-without-a-token
- SAKAZUKIでも設定できるかわからない
- 組織ってあったっけ？
- オーナーしか見れないレポジトリ設定らしい
- 認証オフってセキュリティ的によくない設定？
**トークンありの設定をお願いします🙇**
- レポジトリの設定で、Codecov用のActions secretsの登録が必要
- やり方
- https://docs.codecov.com/docs/codecov-tokens#example-github-actions--official-codecov-action
=> Codecovをv5にアップデート

.github/workflows/fly.yml, config/routes.rb, fly.toml
fix #956
- fly.tomlを最新のドキュメントに従い更新
- 普通のウェブアプリは`http_service`を使いシンプルに設定できるようになった
- 変更点
- すでに存在しない設定を削除した
- 日本リージョンを明示的に指定した
- コンソールコマンドを指定
- 新しいRailsで使える`db:prepare`でDB準備をするようにした
- マシン起動を待つgrace_periodを1s->10sに伸ばした
- vmのCPU・メモリを明示的に指定した
- Actionsの`fly deploy`コマンドから必要ないオプションを削除
- コマンドでなくfly.tomlファイルで指定するようにした
- ヘルスチェック用のルーティング`/up`を追加
- Rails7で追加された便利な機能
- [fly.toml](https://fly.io/docs/reference/configuration/)
- [class Rails::HealthController](https://edgeapi.rubyonrails.org/classes/Rails/HealthController.html)
=> Flyの設定ファイルを新しく設定しなおした

.github/workflows/fly.yml, config/environments/production.rb, config/routes.rb, fly.toml
after #945
close #957
fly proxyが配信してくれるから、Railsの負担を減らせる！
- production環境のRails設定を変更し、public以下の静的ファイルを配信させなくした
=> 静的ファイルの配信をfly proxyに任せる

.ghalint.yaml, .github/workflows/auto-assign.yml, .github/workflows/check.yml, .github/workflows/codeql.yml, .github/workflows/esbuild-bundle-analyzer.yml, .github/workflows/fix-command.yml, .github/workflows/fly.yml, .github/workflows/slash-command-dispatch.yml, .github/workflows/test.yml, .github/zizmor.yml, cli-scripts/run-all-checks.sh
close #943
GitHub Actionsが攻撃を受けたし、Lintも入れておこう。
- Actionlintを追加
- ghalintを追加
- GitHub管理のActionsは信頼してSHAピンではなくv4のようなピンでOKにした
- zizmorを追加
- ピン留め設定がないため、ピンチェックはオフ
- esbuild-bundle-analyzerの`on`イベントの`pull_request_target`は変えれなさそうなので、ここだけ一部ルールを無視
- それぞれ、
- CLIスクリプト
- GitHub Actions
- 新たなLinterに従い修正
=> 🔍Actions用のLinter3種類を追加

README.md, app/controllers/sakes_controller.rb, app/helpers/sakes_helper.rb, app/models/sake.rb, spec/helpers/sakes_helper_spec.rb, spec/requests/sake_request_spec.rb, spec/system/bottle_state_timestamps_spec.rb, spec/system/copy_sakes_spec.rb, spec/system/drink_buttons_spec.rb, spec/system/edit_sake_spec.rb, spec/system/flash_message_spec.rb, spec/system/new_sake_spec.rb, spec/system/sake_form_add_tax_spec.rb, spec/system/sake_form_bindume_date_spec.rb, spec/system/sake_form_bottle_level_spec.rb, spec/system/sake_form_brewery_year_spec.rb, spec/system/sake_form_kura_completion_spec.rb, spec/system/sake_form_photos_spec.rb, spec/system/sake_form_size_spec.rb, spec/system/sake_form_validation_spec.rb, spec/system/user_invitation_spec.rb, spec/views/layouts/_header.html.erb_spec.rb
close #1040 
- 製造年月に不明の選択肢を追加
- BY にすでにあったやつ
- ユニットテストを追加
- ローカルテストでログインできない問題を修正
- Rails 8 にしたときに壊れてた？
- BY との共通化
- 微妙にフォーマット違うので後回し
=> 製造年月で不明（nil）を許可
